SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [Autorisatie2C].[Gebruikersinstellingen] as 
SELECT [Gebruikers-id] = US.[User ID]
	,[Boeken toegest. vanaf] = US.[Allow Posting From]
	,[Boeken toegest. tot] = US.[Allow Posting To]
	,Medewerker = US.[Salespers__Purch_ Code]
	,[Fiatteur-id] = US.[Approver ID]
	,[Limiet voor goedkeuring inkoopbedrag] = US.[Purchase Amount Approval Limit]
	,[Verhuurmutaties fiatteren] = US.[Verhuurmutaties accorderen]
	,Goedkeuringsniveau = US.[Approval Level]

	--,US.[Register Time]
	--,US.[Sales Amount Approval Limit]
	--,US.[Unlimited Sales Approval]
	--,US.[Unlimited Purchase Approval]
	--,US.[Substitute]
	--,US.[E-Mail]
	--,US.[Request Amount Approval Limit]
	--,US.[Unlimited Request Approval]
	--,US.[Time Sheet Admin_]
	--,US.[Allow FA Posting From]
	--,US.[Allow FA Posting To]
	--,US.[Sales Resp_ Ctr_ Filter]
	--,US.[Purchase Resp_ Ctr_ Filter]
	--,US.[Service Resp_ Ctr_ Filter]
	--,US.[Responsibility Center]
	--,US.[Global Dimension 1 Filter]
	--,US.[Deurwaarder]
	--,US.[Blokk_ Dimwijz_ Grootboekrek_]
	--,US.[Grootboekrek_filter Lezen]
	--,US.[Grootboekrek_filter Boeken]
	--,US.[Grootboekrek_filter Invoegen]
	--,US.[Appl_beheerder huurtoeslag]
	--,US.[Boekingsdatum mutabel]
	--,US.[Prolongatie]
	--,US.[Elementposten verwijderen]
	--,US.[Remove Cost Code Entries]
	--,US.[Approver]
	--,US.[Name]
	--,US.[CorrKostSrtRepVrzkMetPosten]
	--,US.[Registratiedatum wijzigen]
	--,US.[Verhuurmutaties fiatteren]
	--,US.[Projecttypefilter]
	--,US.[Permissie budgetw_kladblok]
	--,US.[Permissie heropenen project]
	--,US.[Permissie ingave prognose]
	--,US.[Permissie blokkeren]
	--,US.[Permissie wijzigen status_fase]
	--,US.[Permissie accorderen uren]
	--,US.[Permissie boeken uren]
	--,US.[Permissie budgetwijziging proj]
	--,US.[Permissie handm_invoer kladbl_]
	--,US.[Permissie handm_invoer project]
	--,US.[Reopen Awarded Order]
	--,US.[Gen_ kenmerkenmodule]
	--,US.[Blokkeren financieringen]
	--,US.[Accorderen financieringsmodel]
	--,US.[Accorderen financieringsvorm]
	--,US.[Accorderen kasstroom]
	--,US.[Accorderen rentepercentage]
	--,US.[Salesperson Code]
	--,US.[Postcodecontrole negeren]
	--,US.[Change Complaint Status]
	--,US.[Replacement Purch Inv_Credit]
	--,US.[Publicatiecontrole wijzigen]
	--,US.[Gas_elektra gecontroleerd]
	--,US.[Permissie heropenen reparatiev]
	--,US.[Projectfilter]
	--,US.[S&V-afrekeningen fiatteren]
	--,US.[S&V-afrekeningstatus wijzigen]
	--,US.[Bemiddelingsstatus wijzigen]
	--,US.[Mut_proces ToonAfgehandeld]
	--,US.[Verhuuraanbieding wijzigen]
	--,US.[Bouwnummers vrijgeven]
	--,US.[Permissie heropenen projectfas]
	--,US.[Fixture Type Filter]
	--,US.[Service Call Type Filter]
	--,US.[Interaction Templ_ Code Filter]
	--,US.[Surcharge Allowed]
	--,US.[Dech_ Home Address Allowed]
	--,US.[Dech_ OA Member Allowed]
	--,US.[Manually Close Purchase Order]
	--,US.[Wijzigen fin_boekingsgroep]
	--,US.[Wijzigen geldgever-ID]
	--,US.[Wijzigen grootboekintegratie]
	--,US.[Ignore Maintenance Errors]
	--,US.[Responsibility Center Check]
	--,US.[Remove permissions Em-Planner]
	--,US.[Deduplicate Contacts]
	--,US.[Enable Lync Integration]
	--,US.[Create New Rental Just_]
	--,US.[Activate Cluster Distr Key]
	--,US.[Activate Proj BudgLn Distr Key]
	--,US.[Approval Administrator]
	--,US.[Overrule TenantAgreesToCosts]
	--,US.[Change Lib_ Contract Ind_]
	--,US.[Activate Change OGE Adm_ Owner]
	--,US.[Bailiff No_]
	--,US.[Send AE Payment Request]
FROM [Empire].[Staedion$User Setup] AS US
GO
EXEC sp_addextendedproperty N'Auteur', N'JvdW', 'SCHEMA', N'Autorisatie2C', 'VIEW', N'Gebruikersinstellingen', NULL, NULL
GO
EXEC sp_addextendedproperty N'CNSAfhankelijk', N'Nee', 'SCHEMA', N'Autorisatie2C', 'VIEW', N'Gebruikersinstellingen', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'View op Empire-tabel [User Setup]', 'SCHEMA', N'Autorisatie2C', 'VIEW', N'Gebruikersinstellingen', NULL, NULL
GO
EXEC sp_addextendedproperty N'VoorbeeldAanroep', N'select * from staedion_dm.Autorisatie2C.[Gebruiker]', 'SCHEMA', N'Autorisatie2C', 'VIEW', N'Gebruikersinstellingen', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'BRON: ...', 'SCHEMA', N'Autorisatie2C', 'VIEW', N'Gebruikersinstellingen', 'COLUMN', N'Medewerker'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BRON: ...', 'SCHEMA', N'Autorisatie2C', 'VIEW', N'Gebruikersinstellingen', 'COLUMN', N'Verhuurmutaties fiatteren'
GO
