SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE view [Leefbaarheid].[CBSBuurtgegevens] as

SELECT DISTINCT ELS.BuurtCode
	  ,[Jaar] = 2016 
      ,[AantalInwoners] = [AantalInwoners_5]
      ,[Mannen] = [Mannen_6]
      ,[Vrouwen] = [Vrouwen_7]
      ,[k_0Tot15Jaar] = [k_0Tot15Jaar_8]
      ,[k_15Tot25Jaar] = [k_15Tot25Jaar_9]
      ,[k_25Tot45Jaar] = [k_25Tot45Jaar_10]
      ,[k_45Tot65Jaar] = [k_45Tot65Jaar_11]
      ,[k_65JaarOfOuder] = [k_65JaarOfOuder_12]
      ,[Ongehuwd] = [Ongehuwd_13]
      ,[Gehuwd] = [Gehuwd_14]
      ,[Gescheiden] = [Gescheiden_15]
      ,[Verweduwd] = [Verweduwd_16]
      ,[WestersTotaal] = [WestersTotaal_17]
      ,[NietWestersTotaal] = [NietWestersTotaal_18]
      ,[Marokko] = [Marokko_19]
      ,[NederlandseAntillenEnAruba] = [NederlandseAntillenEnAruba_20]
      ,[Suriname] = [Suriname_21]
      ,[Turkije] = [Turkije_22]
      ,[OverigNietWesters] = [OverigNietWesters_23]
      ,[GeboorteTotaal] = [GeboorteTotaal_24]
      ,[GeboorteRelatief] = [GeboorteRelatief_25]
      ,[SterfteTotaal] = [SterfteTotaal_26]
      ,[SterfteRelatief] = [SterfteRelatief_27]
      ,[HuishoudensTotaal] = [HuishoudensTotaal_28]
      ,[Eenpersoonshuishoudens] = [Eenpersoonshuishoudens_29]
      ,[HuishoudensZonderKinderen] = [HuishoudensZonderKinderen_30]
      ,[HuishoudensMetKinderen] = [HuishoudensMetKinderen_31]
      ,[GemiddeldeHuishoudensgrootte] = [GemiddeldeHuishoudensgrootte_32]
      ,[Bevolkingsdichtheid] = [Bevolkingsdichtheid_33]
      ,[Woningvoorraad] = [Woningvoorraad_34]
      ,[GemiddeldeWoningwaarde] = [GemiddeldeWoningwaarde_35]
      ,[PercentageEengezinswoning] = [PercentageEengezinswoning_36]
      ,[PercentageMeergezinswoning] = [PercentageMeergezinswoning_37]
      ,[PercentageBewoond] = [PercentageBewoond_38]
      ,[PercentageOnbewoond] = [PercentageOnbewoond_39]
      ,[Koopwoningen] = [Koopwoningen_40]
      ,[HuurwoningenTotaal] = [HuurwoningenTotaal_41]
      ,[InBezitWoningcorporatie] = [InBezitWoningcorporatie_42]
      ,[InBezitOverigeVerhuurders] = [InBezitOverigeVerhuurders_43]
      ,[EigendomOnbekend] = [EigendomOnbekend_44]
      ,[BouwjaarVoor2000] = [BouwjaarVoor2000_45]
      ,[BouwjaarVanaf2000] = [BouwjaarVanaf2000_46]
      ,[GemiddeldElektriciteitsverbruikTotaal] = [GemiddeldElektriciteitsverbruikTotaal_47]
      ,[kWhAppartement] = [Appartement_48]
      ,[kWhTussenwoning] =[Tussenwoning_49]
      ,[kWhHoekwoning] = [Hoekwoning_50]
      ,[kWhTweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_51] like '%.%', null, [TweeOnderEenKapWoning_51])
      ,[kWhVrijstaandeWoning] = iif([VrijstaandeWoning_52] like '%.%', null, [VrijstaandeWoning_52])
      ,[kWhHuurwoning] = [Huurwoning_53]
      ,[kWhEigenWoning] = [EigenWoning_54]
      ,[GemiddeldAardgasverbruikTotaal] = [GemiddeldAardgasverbruikTotaal_55]
      ,[m3Appartement] = [Appartement_56]
      ,[m3Tussenwoning] = [Tussenwoning_57]
      ,[m3Hoekwoning] = [Hoekwoning_58]
      ,[m3TweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_59] like '%.%', null, [TweeOnderEenKapWoning_59])
      ,[m3VrijstaandeWoning] = iif([VrijstaandeWoning_60] like '%.%', null, [VrijstaandeWoning_60])
      ,[m3Huurwoning] = [Huurwoning_61]
      ,[m3EigenWoning] = [EigenWoning_62]
      ,[PercentageWoningenMetStadsverwarming] = iif([PercentageWoningenMetStadsverwarming_63] like '%.%', null, [PercentageWoningenMetStadsverwarming_63])
      ,[AantalInkomensontvangers] = [AantalInkomensontvangers_64]
      ,[GemiddeldInkomenPerInkomensontvanger] = iif([GemiddeldInkomenPerInkomensontvanger_65] like '%.%', null, [GemiddeldInkomenPerInkomensontvanger_65])
      ,[GemiddeldInkomenPerInwoner] = iif([GemiddeldInkomenPerInwoner_66] like '%.%', null, [GemiddeldInkomenPerInwoner_66])
      ,[k_40PersonenMetLaagsteInkomen] = [k_40PersonenMetLaagsteInkomen_67]
      ,[k_20PersonenMetHoogsteInkomen] = [k_20PersonenMetHoogsteInkomen_68]
      ,[Actieven1575Jaar] = [Actieven1575Jaar_69]
      ,[k_40HuishoudensMetLaagsteInkomen] = iif([k_40HuishoudensMetLaagsteInkomen_70] like '%.%', null, [k_40HuishoudensMetLaagsteInkomen_70])
      ,[k_20HuishoudensMetHoogsteInkomen] = iif([k_20HuishoudensMetHoogsteInkomen_71] like '%.%', null, [k_20HuishoudensMetHoogsteInkomen_71])
      ,[HuishoudensMetEenLaagInkomen] = iif([HuishoudensMetEenLaagInkomen_72] like '%.%', null, [HuishoudensMetEenLaagInkomen_72])
      ,[HuishOnderOfRondSociaalMinimum] = iif([HuishOnderOfRondSociaalMinimum_73] like '%.%', null, [HuishOnderOfRondSociaalMinimum_73])
      ,[PersonenPerSoortUitkeringBijstand] = [PersonenPerSoortUitkeringBijstand_74]
      ,[PersonenPerSoortUitkeringAO] = [PersonenPerSoortUitkeringAO_75]
      ,[PersonenPerSoortUitkeringWW] = [PersonenPerSoortUitkeringWW_76]
      ,[PersonenPerSoortUitkeringAOW] = [PersonenPerSoortUitkeringAOW_77]
      ,[BedrijfsvestigingenTotaal] = [BedrijfsvestigingenTotaal_78]
      ,[ALandbouwBosbouwEnVisserij] = [ALandbouwBosbouwEnVisserij_79]
      ,[BFNijverheidEnEnergie] = [BFNijverheidEnEnergie_80]
      ,[GIHandelEnHoreca] = [GIHandelEnHoreca_81]
      ,[HJVervoerInformatieEnCommunicatie] = [HJVervoerInformatieEnCommunicatie_82]
      ,[KLFinancieleDienstenOnroerendGoed] = [KLFinancieleDienstenOnroerendGoed_83]
      ,[MNZakelijkeDienstverlening] = [MNZakelijkeDienstverlening_84]
      ,[RUCultuurRecreatieOverigeDiensten] = [RUCultuurRecreatieOverigeDiensten_85]
      ,[PersonenautoSTotaal] = [PersonenautoSTotaal_86]
      ,[PersonenautoSJongerDan6Jaar] = [PersonenautoSJongerDan6Jaar_87]
      ,[PersonenautoS6JaarEnOuder] = [PersonenautoS6JaarEnOuder_88]
      ,[PersonenautoSBrandstofBenzine] = [PersonenautoSBrandstofBenzine_89]
      ,[PersonenautoSOverigeBrandstof] = [PersonenautoSOverigeBrandstof_90]
      ,[PersonenautoSPerHuishouden] = iif([PersonenautoSPerHuishouden_91] like '%.%', null, [PersonenautoSPerHuishouden_91])
      ,[PersonenautoSNaarOppervlakte] = [PersonenautoSNaarOppervlakte_92]
      ,[Bedrijfsmotorvoertuigen] = [Bedrijfsmotorvoertuigen_93]
      ,[Motorfietsen] = [Motorfietsen_94]
      ,[AfstandTotHuisartsenpraktijk] = [AfstandTotHuisartsenpraktijk_95]
      ,[AfstandTotGroteSupermarkt] = [AfstandTotGroteSupermarkt_96]
      ,[AfstandTotKinderdagverblijf] = [AfstandTotKinderdagverblijf_97]
      ,[AfstandTotSchool] = [AfstandTotSchool_98]
      ,[ScholenBinnen3Km] = [ScholenBinnen3Km_99]
      ,[OppervlakteTotaal] = [OppervlakteTotaal_100]
      ,[OppervlakteLand] = [OppervlakteLand_101]
      ,[OppervlakteWater] = [OppervlakteWater_102]
      ,[MeestVoorkomendePostcode] = [MeestVoorkomendePostcode_103]
      ,[Dekkingspercentage] = [Dekkingspercentage_104]
      ,[MateVanStedelijkheid] = [MateVanStedelijkheid_105]
      ,[Omgevingsadressendichtheid] = [Omgevingsadressendichtheid_106]
      ,[TotaalDiefstalUitWoningSchuurED] = [TotaalDiefstalUitWoningSchuurED_107]
      ,[VernielingMisdrijfTegenOpenbareOrde] = [VernielingMisdrijfTegenOpenbareOrde_108]
      ,[GeweldsEnSeksueleMisdrijven] = [GeweldsEnSeksueleMisdrijven_109]
  FROM [empire_staedion_data].[bik].[CBS_BuurtGegevens2016] as CBS
  inner join empire_staedion_data.bik.ELS_ClusternummerBuurtCode as ELS on (N'BU' + RIGHT(N'00000000' + CAST(ELS.BuurtCode AS nvarchar), 8)) = CBS.Codering_3
  where CBS.Codering_3 like 'BU%' and CBS.AantalInwoners_5 <> 0

  union all

  SELECT DISTINCT ELS.BuurtCode
	  ,[Jaar] = 2017
      ,[AantalInwoners] = [AantalInwoners_5]
      ,[Mannen] = [Mannen_6]
      ,[Vrouwen] = [Vrouwen_7]
      ,[k_0Tot15Jaar] = [k_0Tot15Jaar_8]
      ,[k_15Tot25Jaar] = [k_15Tot25Jaar_9]
      ,[k_25Tot45Jaar] = [k_25Tot45Jaar_10]
      ,[k_45Tot65Jaar] = [k_45Tot65Jaar_11]
      ,[k_65JaarOfOuder] = [k_65JaarOfOuder_12]
      ,[Ongehuwd] = [Ongehuwd_13]
      ,[Gehuwd] = [Gehuwd_14]
      ,[Gescheiden] = [Gescheiden_15]
      ,[Verweduwd] = [Verweduwd_16]
      ,[WestersTotaal] = [WestersTotaal_17]
      ,[NietWestersTotaal] = [NietWestersTotaal_18]
      ,[Marokko] = [Marokko_19]
      ,[NederlandseAntillenEnAruba] = [NederlandseAntillenEnAruba_20]
      ,[Suriname] = [Suriname_21]
      ,[Turkije] = [Turkije_22]
      ,[OverigNietWesters] = [OverigNietWesters_23]
      ,[GeboorteTotaal] = [GeboorteTotaal_24]
      ,[GeboorteRelatief] = [GeboorteRelatief_25]
      ,[SterfteTotaal] = [SterfteTotaal_26]
      ,[SterfteRelatief] = [SterfteRelatief_27]
      ,[HuishoudensTotaal] = [HuishoudensTotaal_28]
      ,[Eenpersoonshuishoudens] = [Eenpersoonshuishoudens_29]
      ,[HuishoudensZonderKinderen] = [HuishoudensZonderKinderen_30]
      ,[HuishoudensMetKinderen] = [HuishoudensMetKinderen_31]
      ,[GemiddeldeHuishoudensgrootte] = [GemiddeldeHuishoudensgrootte_32]
      ,[Bevolkingsdichtheid] = [Bevolkingsdichtheid_33]
      ,[Woningvoorraad] = [Woningvoorraad_34]
      ,[GemiddeldeWoningwaarde] = [GemiddeldeWoningwaarde_35]
      ,[PercentageEengezinswoning] = [PercentageEengezinswoning_36]
      ,[PercentageMeergezinswoning] = [PercentageMeergezinswoning_37]
      ,[PercentageBewoond] = [PercentageBewoond_38]
      ,[PercentageOnbewoond] = [PercentageOnbewoond_39]
      ,[Koopwoningen] = [Koopwoningen_40]
      ,[HuurwoningenTotaal] = [HuurwoningenTotaal_41]
      ,[InBezitWoningcorporatie] = [InBezitWoningcorporatie_42]
      ,[InBezitOverigeVerhuurders] = [InBezitOverigeVerhuurders_43]
      ,[EigendomOnbekend] = [EigendomOnbekend_44]
      ,[BouwjaarVoor2000] = [BouwjaarVoor2000_45]
      ,[BouwjaarVanaf2000] = [BouwjaarVanaf2000_46]
      ,[GemiddeldElektriciteitsverbruikTotaal] = [GemiddeldElektriciteitsverbruikTotaal_47]
      ,[kWhAppartement] = [Appartement_48]
      ,[kWhTussenwoning] =[Tussenwoning_49]
      ,[kWhHoekwoning] = [Hoekwoning_50]
      ,[kWhTweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_51] like '%.%', null, [TweeOnderEenKapWoning_51])
      ,[kWhVrijstaandeWoning] = iif([VrijstaandeWoning_52] like '%.%', null, [VrijstaandeWoning_52])
      ,[kWhHuurwoning] = [Huurwoning_53]
      ,[kWhEigenWoning] = [EigenWoning_54]
      ,[GemiddeldAardgasverbruikTotaal] = [GemiddeldAardgasverbruikTotaal_55]
      ,[m3Appartement] = [Appartement_56]
      ,[m3Tussenwoning] = [Tussenwoning_57]
      ,[m3Hoekwoning] = [Hoekwoning_58]
      ,[m3TweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_59] like '%.%', null, [TweeOnderEenKapWoning_59])
      ,[m3VrijstaandeWoning] = iif([VrijstaandeWoning_60] like '%.%', null, [VrijstaandeWoning_60])
      ,[m3Huurwoning] = [Huurwoning_61]
      ,[m3EigenWoning] = [EigenWoning_62]
      ,[PercentageWoningenMetStadsverwarming] = iif([PercentageWoningenMetStadsverwarming_63] like '%.%', null, [PercentageWoningenMetStadsverwarming_63])
      ,[AantalInkomensontvangers] = [AantalInkomensontvangers_64]
      ,[GemiddeldInkomenPerInkomensontvanger] = iif([GemiddeldInkomenPerInkomensontvanger_65] like '%.%', null, [GemiddeldInkomenPerInkomensontvanger_65])
      ,[GemiddeldInkomenPerInwoner] = iif([GemiddeldInkomenPerInwoner_66] like '%.%', null, [GemiddeldInkomenPerInwoner_66])
      ,[k_40PersonenMetLaagsteInkomen] = [k_40PersonenMetLaagsteInkomen_67]
      ,[k_20PersonenMetHoogsteInkomen] = [k_20PersonenMetHoogsteInkomen_68]
      ,[Actieven1575Jaar] = [Actieven1575Jaar_69]
      ,[k_40HuishoudensMetLaagsteInkomen] = iif([k_40HuishoudensMetLaagsteInkomen_70] like '%.%', null, [k_40HuishoudensMetLaagsteInkomen_70])
      ,[k_20HuishoudensMetHoogsteInkomen] = iif([k_20HuishoudensMetHoogsteInkomen_71] like '%.%', null, [k_20HuishoudensMetHoogsteInkomen_71])
      ,[HuishoudensMetEenLaagInkomen] = iif([HuishoudensMetEenLaagInkomen_72] like '%.%', null, [HuishoudensMetEenLaagInkomen_72])
      ,[HuishOnderOfRondSociaalMinimum] = iif([HuishOnderOfRondSociaalMinimum_73] like '%.%', null, [HuishOnderOfRondSociaalMinimum_73])
      ,[PersonenPerSoortUitkeringBijstand] = [PersonenPerSoortUitkeringBijstand_74]
      ,[PersonenPerSoortUitkeringAO] = [PersonenPerSoortUitkeringAO_75]
      ,[PersonenPerSoortUitkeringWW] = [PersonenPerSoortUitkeringWW_76]
      ,[PersonenPerSoortUitkeringAOW] = [PersonenPerSoortUitkeringAOW_77]
      ,[BedrijfsvestigingenTotaal] = [BedrijfsvestigingenTotaal_78]
      ,[ALandbouwBosbouwEnVisserij] = [ALandbouwBosbouwEnVisserij_79]
      ,[BFNijverheidEnEnergie] = [BFNijverheidEnEnergie_80]
      ,[GIHandelEnHoreca] = [GIHandelEnHoreca_81]
      ,[HJVervoerInformatieEnCommunicatie] = [HJVervoerInformatieEnCommunicatie_82]
      ,[KLFinancieleDienstenOnroerendGoed] = [KLFinancieleDienstenOnroerendGoed_83]
      ,[MNZakelijkeDienstverlening] = [MNZakelijkeDienstverlening_84]
      ,[RUCultuurRecreatieOverigeDiensten] = [RUCultuurRecreatieOverigeDiensten_85]
      ,[PersonenautoSTotaal] = [PersonenautoSTotaal_86]
      ,[PersonenautoSJongerDan6Jaar] = [PersonenautoSJongerDan6Jaar_87]
      ,[PersonenautoS6JaarEnOuder] = [PersonenautoS6JaarEnOuder_88]
      ,[PersonenautoSBrandstofBenzine] = [PersonenautoSBrandstofBenzine_89]
      ,[PersonenautoSOverigeBrandstof] = [PersonenautoSOverigeBrandstof_90]
      ,[PersonenautoSPerHuishouden] = iif([PersonenautoSPerHuishouden_91] like '%.%', null, [PersonenautoSPerHuishouden_91])
      ,[PersonenautoSNaarOppervlakte] = [PersonenautoSNaarOppervlakte_92]
      ,[Bedrijfsmotorvoertuigen] = null
      ,[Motorfietsen] = [Motorfietsen_93]
      ,[AfstandTotHuisartsenpraktijk] = [AfstandTotHuisartsenpraktijk_94]
      ,[AfstandTotGroteSupermarkt] = [AfstandTotGroteSupermarkt_95]
      ,[AfstandTotKinderdagverblijf] = [AfstandTotKinderdagverblijf_96]
      ,[AfstandTotSchool] = [AfstandTotSchool_97]
      ,[ScholenBinnen3Km] = [ScholenBinnen3Km_98]
      ,[OppervlakteTotaal] = [OppervlakteTotaal_99]
      ,[OppervlakteLand] = [OppervlakteLand_100]
      ,[OppervlakteWater] = [OppervlakteWater_101]
      ,[MeestVoorkomendePostcode] = [MeestVoorkomendePostcode_102]
      ,[Dekkingspercentage] = [Dekkingspercentage_103]
      ,[MateVanStedelijkheid] = [MateVanStedelijkheid_104]
      ,[Omgevingsadressendichtheid] = [Omgevingsadressendichtheid_105]
      ,[TotaalDiefstalUitWoningSchuurED] = [TotaalDiefstalUitWoningSchuurED_106]
      ,[VernielingMisdrijfTegenOpenbareOrde] = [VernielingMisdrijfTegenOpenbareOrde_107]
      ,[GeweldsEnSeksueleMisdrijven] = [GeweldsEnSeksueleMisdrijven_108]
  FROM [empire_staedion_data].[bik].[CBS_BuurtGegevens2017] as CBS
  inner join empire_staedion_data.bik.ELS_ClusternummerBuurtCode as ELS on (N'BU' + RIGHT(N'00000000' + CAST(ELS.BuurtCode AS nvarchar), 8)) = CBS.Codering_3
  where CBS.Codering_3 like 'BU%' and CBS.AantalInwoners_5 <> 0

  union all

  SELECT DISTINCT ELS.BuurtCode
	  ,[Jaar] = 2018
      ,[AantalInwoners] = [AantalInwoners_5]
      ,[Mannen] = [Mannen_6]
      ,[Vrouwen] = [Vrouwen_7]
      ,[k_0Tot15Jaar] = [k_0Tot15Jaar_8]
      ,[k_15Tot25Jaar] = [k_15Tot25Jaar_9]
      ,[k_25Tot45Jaar] = [k_25Tot45Jaar_10]
      ,[k_45Tot65Jaar] = [k_45Tot65Jaar_11]
      ,[k_65JaarOfOuder] = [k_65JaarOfOuder_12]
      ,[Ongehuwd] = [Ongehuwd_13]
      ,[Gehuwd] = [Gehuwd_14]
      ,[Gescheiden] = [Gescheiden_15]
      ,[Verweduwd] = [Verweduwd_16]
      ,[WestersTotaal] = [WestersTotaal_17]
      ,[NietWestersTotaal] = [NietWestersTotaal_18]
      ,[Marokko] = [Marokko_19]
      ,[NederlandseAntillenEnAruba] = [NederlandseAntillenEnAruba_20]
      ,[Suriname] = [Suriname_21]
      ,[Turkije] = [Turkije_22]
      ,[OverigNietWesters] = [OverigNietWesters_23]
      ,[GeboorteTotaal] = [GeboorteTotaal_24]
      ,[GeboorteRelatief] = [GeboorteRelatief_25]
      ,[SterfteTotaal] = [SterfteTotaal_26]
      ,[SterfteRelatief] = [SterfteRelatief_27]
      ,[HuishoudensTotaal] = [HuishoudensTotaal_28]
      ,[Eenpersoonshuishoudens] = [Eenpersoonshuishoudens_29]
      ,[HuishoudensZonderKinderen] = [HuishoudensZonderKinderen_30]
      ,[HuishoudensMetKinderen] = [HuishoudensMetKinderen_31]
      ,[GemiddeldeHuishoudensgrootte] = [GemiddeldeHuishoudensgrootte_32]
      ,[Bevolkingsdichtheid] = [Bevolkingsdichtheid_33]
      ,[Woningvoorraad] = [Woningvoorraad_34]
      ,[GemiddeldeWoningwaarde] = [GemiddeldeWoningwaarde_35]
      ,[PercentageEengezinswoning] = [PercentageEengezinswoning_36]
      ,[PercentageMeergezinswoning] = [PercentageMeergezinswoning_37]
      ,[PercentageBewoond] = [PercentageBewoond_38]
      ,[PercentageOnbewoond] = [PercentageOnbewoond_39]
      ,[Koopwoningen] = [Koopwoningen_40]
      ,[HuurwoningenTotaal] = [HuurwoningenTotaal_41]
      ,[InBezitWoningcorporatie] = [InBezitWoningcorporatie_42]
      ,[InBezitOverigeVerhuurders] = [InBezitOverigeVerhuurders_43]
      ,[EigendomOnbekend] = [EigendomOnbekend_44]
      ,[BouwjaarVoor2000] = [BouwjaarVoor2000_45]
      ,[BouwjaarVanaf2000] = [BouwjaarVanaf2000_46]
      ,[GemiddeldElektriciteitsverbruikTotaal] = [GemiddeldElektriciteitsverbruikTotaal_47]
      ,[kWhAppartement] = [Appartement_48]
      ,[kWhTussenwoning] =[Tussenwoning_49]
      ,[kWhHoekwoning] = [Hoekwoning_50]
      ,[kWhTweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_51] like '%.%', null, [TweeOnderEenKapWoning_51])
      ,[kWhVrijstaandeWoning] = iif([VrijstaandeWoning_52] like '%.%', null, [VrijstaandeWoning_52])
      ,[kWhHuurwoning] = [Huurwoning_53]
      ,[kWhEigenWoning] = [EigenWoning_54]
      ,[GemiddeldAardgasverbruikTotaal] = [GemiddeldAardgasverbruikTotaal_55]
      ,[m3Appartement] = [Appartement_56]
      ,[m3Tussenwoning] = [Tussenwoning_57]
      ,[m3Hoekwoning] = [Hoekwoning_58]
      ,[m3TweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_59] like '%.%', null, [TweeOnderEenKapWoning_59])
      ,[m3VrijstaandeWoning] = iif([VrijstaandeWoning_60] like '%.%', null, [VrijstaandeWoning_60])
      ,[m3Huurwoning] = [Huurwoning_61]
      ,[m3EigenWoning] = [EigenWoning_62]
      ,[PercentageWoningenMetStadsverwarming] = iif([PercentageWoningenMetStadsverwarming_63] like '%.%', null, [PercentageWoningenMetStadsverwarming_63])
      ,[AantalInkomensontvangers] = [AantalInkomensontvangers_64]
      ,[GemiddeldInkomenPerInkomensontvanger] = iif([GemiddeldInkomenPerInkomensontvanger_65] like '%.%', null, [GemiddeldInkomenPerInkomensontvanger_65])
      ,[GemiddeldInkomenPerInwoner] = iif([GemiddeldInkomenPerInwoner_66] like '%.%', null, [GemiddeldInkomenPerInwoner_66])
      ,[k_40PersonenMetLaagsteInkomen] = [k_40PersonenMetLaagsteInkomen_67]
      ,[k_20PersonenMetHoogsteInkomen] = [k_20PersonenMetHoogsteInkomen_68]
      ,[Actieven1575Jaar] = [Actieven1575Jaar_69]
      ,[k_40HuishoudensMetLaagsteInkomen] = iif([k_40HuishoudensMetLaagsteInkomen_70] like '%.%', null, [k_40HuishoudensMetLaagsteInkomen_70])
      ,[k_20HuishoudensMetHoogsteInkomen] = iif([k_20HuishoudensMetHoogsteInkomen_71] like '%.%', null, [k_20HuishoudensMetHoogsteInkomen_71])
      ,[HuishoudensMetEenLaagInkomen] = iif([HuishoudensMetEenLaagInkomen_72] like '%.%', null, [HuishoudensMetEenLaagInkomen_72])
      ,[HuishOnderOfRondSociaalMinimum] = iif([HuishOnderOfRondSociaalMinimum_73] like '%.%', null, [HuishOnderOfRondSociaalMinimum_73])
      ,[PersonenPerSoortUitkeringBijstand] = [PersonenPerSoortUitkeringBijstand_74]
      ,[PersonenPerSoortUitkeringAO] = [PersonenPerSoortUitkeringAO_75]
      ,[PersonenPerSoortUitkeringWW] = [PersonenPerSoortUitkeringWW_76]
      ,[PersonenPerSoortUitkeringAOW] = [PersonenPerSoortUitkeringAOW_77]
      ,[BedrijfsvestigingenTotaal] = [BedrijfsvestigingenTotaal_81]
      ,[ALandbouwBosbouwEnVisserij] = [ALandbouwBosbouwEnVisserij_82]
      ,[BFNijverheidEnEnergie] = [BFNijverheidEnEnergie_83]
      ,[GIHandelEnHoreca] = [GIHandelEnHoreca_84]
      ,[HJVervoerInformatieEnCommunicatie] = [HJVervoerInformatieEnCommunicatie_85]
      ,[KLFinancieleDienstenOnroerendGoed] = [KLFinancieleDienstenOnroerendGoed_86]
      ,[MNZakelijkeDienstverlening] = [MNZakelijkeDienstverlening_87]
      ,[RUCultuurRecreatieOverigeDiensten] = [RUCultuurRecreatieOverigeDiensten_88]
      ,[PersonenautoSTotaal] = [PersonenautoSTotaal_89]
      ,[PersonenautoSJongerDan6Jaar] = null
      ,[PersonenautoS6JaarEnOuder] = null
      ,[PersonenautoSBrandstofBenzine] = [PersonenautoSBrandstofBenzine_90]
      ,[PersonenautoSOverigeBrandstof] = [PersonenautoSOverigeBrandstof_91]
      ,[PersonenautoSPerHuishouden] = iif([PersonenautoSPerHuishouden_92] like '%.%', null, [PersonenautoSPerHuishouden_92])
      ,[PersonenautoSNaarOppervlakte] = [PersonenautoSNaarOppervlakte_93]
      ,[Bedrijfsmotorvoertuigen] = null
      ,[Motorfietsen] = [Motorfietsen_94]
      ,[AfstandTotHuisartsenpraktijk] = [AfstandTotHuisartsenpraktijk_95]
      ,[AfstandTotGroteSupermarkt] = [AfstandTotGroteSupermarkt_96]
      ,[AfstandTotKinderdagverblijf] = [AfstandTotKinderdagverblijf_97]
      ,[AfstandTotSchool] = [AfstandTotSchool_98]
      ,[ScholenBinnen3Km] = [ScholenBinnen3Km_99]
      ,[OppervlakteTotaal] = [OppervlakteTotaal_100]
      ,[OppervlakteLand] = [OppervlakteLand_101]
      ,[OppervlakteWater] = [OppervlakteWater_102]
      ,[MeestVoorkomendePostcode] = [MeestVoorkomendePostcode_103]
      ,[Dekkingspercentage] = [Dekkingspercentage_104]
      ,[MateVanStedelijkheid] = [MateVanStedelijkheid_105]
      ,[Omgevingsadressendichtheid] = [Omgevingsadressendichtheid_106]
      ,[TotaalDiefstalUitWoningSchuurED] = [TotaalDiefstalUitWoningSchuurED_78]
      ,[VernielingMisdrijfTegenOpenbareOrde] = [VernielingMisdrijfTegenOpenbareOrde_79]
      ,[GeweldsEnSeksueleMisdrijven] = [GeweldsEnSeksueleMisdrijven_80]
  FROM [empire_staedion_data].[bik].[CBS_BuurtGegevens2018] as CBS
  inner join empire_staedion_data.bik.ELS_ClusternummerBuurtCode as ELS on (N'BU' + RIGHT(N'00000000' + CAST(ELS.BuurtCode AS nvarchar), 8)) = CBS.Codering_3
  where CBS.Codering_3 like 'BU%' and CBS.AantalInwoners_5 <> 0

  union all

  SELECT DISTINCT ELS.BuurtCode
	  ,[Jaar] = 2019
      ,[AantalInwoners] = [AantalInwoners_5]
      ,[Mannen] = [Mannen_6]
      ,[Vrouwen] = [Vrouwen_7]
      ,[k_0Tot15Jaar] = [k_0Tot15Jaar_8]
      ,[k_15Tot25Jaar] = [k_15Tot25Jaar_9]
      ,[k_25Tot45Jaar] = [k_25Tot45Jaar_10]
      ,[k_45Tot65Jaar] = [k_45Tot65Jaar_11]
      ,[k_65JaarOfOuder] = [k_65JaarOfOuder_12]
      ,[Ongehuwd] = [Ongehuwd_13]
      ,[Gehuwd] = [Gehuwd_14]
      ,[Gescheiden] = [Gescheiden_15]
      ,[Verweduwd] = [Verweduwd_16]
      ,[WestersTotaal] = [WestersTotaal_17]
      ,[NietWestersTotaal] = [NietWestersTotaal_18]
      ,[Marokko] = [Marokko_19]
      ,[NederlandseAntillenEnAruba] = [NederlandseAntillenEnAruba_20]
      ,[Suriname] = [Suriname_21]
      ,[Turkije] = [Turkije_22]
      ,[OverigNietWesters] = [OverigNietWesters_23]
      ,[GeboorteTotaal] = [GeboorteTotaal_24]
      ,[GeboorteRelatief] = [GeboorteRelatief_25]
      ,[SterfteTotaal] = [SterfteTotaal_26]
      ,[SterfteRelatief] = [SterfteRelatief_27]
      ,[HuishoudensTotaal] = [HuishoudensTotaal_28]
      ,[Eenpersoonshuishoudens] = [Eenpersoonshuishoudens_29]
      ,[HuishoudensZonderKinderen] = [HuishoudensZonderKinderen_30]
      ,[HuishoudensMetKinderen] = [HuishoudensMetKinderen_31]
      ,[GemiddeldeHuishoudensgrootte] = [GemiddeldeHuishoudensgrootte_32]
      ,[Bevolkingsdichtheid] = [Bevolkingsdichtheid_33]
      ,[Woningvoorraad] = [Woningvoorraad_34]
      ,[GemiddeldeWoningwaarde] = [GemiddeldeWoningwaarde_35]
      ,[PercentageEengezinswoning] = [PercentageEengezinswoning_36]
      ,[PercentageMeergezinswoning] = [PercentageMeergezinswoning_37]
      ,[PercentageBewoond] = [PercentageBewoond_38]
      ,[PercentageOnbewoond] = [PercentageOnbewoond_39]
      ,[Koopwoningen] = [Koopwoningen_40]
      ,[HuurwoningenTotaal] = [HuurwoningenTotaal_41]
      ,[InBezitWoningcorporatie] = [InBezitWoningcorporatie_42]
      ,[InBezitOverigeVerhuurders] = [InBezitOverigeVerhuurders_43]
      ,[EigendomOnbekend] = [EigendomOnbekend_44]
      ,[BouwjaarVoor2000] = [BouwjaarVoor2000_45]
      ,[BouwjaarVanaf2000] = [BouwjaarVanaf2000_46]
      ,[GemiddeldElektriciteitsverbruikTotaal] = [GemiddeldElektriciteitsverbruikTotaal_47]
      ,[kWhAppartement] = [Appartement_48]
      ,[kWhTussenwoning] =[Tussenwoning_49]
      ,[kWhHoekwoning] = [Hoekwoning_50]
      ,[kWhTweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_51] like '%.%', null, [TweeOnderEenKapWoning_51])
      ,[kWhVrijstaandeWoning] = iif([VrijstaandeWoning_52] like '%.%', null, [VrijstaandeWoning_52])
      ,[kWhHuurwoning] = [Huurwoning_53]
      ,[kWhEigenWoning] = [EigenWoning_54]
      ,[GemiddeldAardgasverbruikTotaal] = [GemiddeldAardgasverbruikTotaal_55]
      ,[m3Appartement] = [Appartement_56]
      ,[m3Tussenwoning] = [Tussenwoning_57]
      ,[m3Hoekwoning] = [Hoekwoning_58]
      ,[m3TweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_59] like '%.%', null, [TweeOnderEenKapWoning_59])
      ,[m3VrijstaandeWoning] = iif([VrijstaandeWoning_60] like '%.%', null, [VrijstaandeWoning_60])
      ,[m3Huurwoning] = [Huurwoning_61]
      ,[m3EigenWoning] = [EigenWoning_62]
      ,[PercentageWoningenMetStadsverwarming] = iif([PercentageWoningenMetStadsverwarming_63] like '%.%', null, [PercentageWoningenMetStadsverwarming_63])
      ,[AantalInkomensontvangers] = iif([AantalInkomensontvangers_64] like '%.%', null, [AantalInkomensontvangers_64])
      ,[GemiddeldInkomenPerInkomensontvanger] = iif([GemiddeldInkomenPerInkomensontvanger_65] like '%.%', null, [GemiddeldInkomenPerInkomensontvanger_65])
      ,[GemiddeldInkomenPerInwoner] = iif([GemiddeldInkomenPerInwoner_66] like '%.%', null, [GemiddeldInkomenPerInwoner_66])
      ,[k_40PersonenMetLaagsteInkomen] = iif([k_40PersonenMetLaagsteInkomen_67] like '%.%', null, [k_40PersonenMetLaagsteInkomen_67])
      ,[k_20PersonenMetHoogsteInkomen] = iif([k_20PersonenMetHoogsteInkomen_68] like '%.%', null, [k_20PersonenMetHoogsteInkomen_68])
      ,[Actieven1575Jaar] = iif([Actieven1575Jaar_69] like '%.%', null, [Actieven1575Jaar_69])
      ,[k_40HuishoudensMetLaagsteInkomen] = iif([k_40HuishoudensMetLaagsteInkomen_70] like '%.%', null, [k_40HuishoudensMetLaagsteInkomen_70])
      ,[k_20HuishoudensMetHoogsteInkomen] = iif([k_20HuishoudensMetHoogsteInkomen_71] like '%.%', null, [k_20HuishoudensMetHoogsteInkomen_71])
      ,[HuishoudensMetEenLaagInkomen] = iif([HuishoudensMetEenLaagInkomen_72] like '%.%', null, [HuishoudensMetEenLaagInkomen_72])
      ,[HuishOnderOfRondSociaalMinimum] = iif([HuishOnderOfRondSociaalMinimum_73] like '%.%', null, [HuishOnderOfRondSociaalMinimum_73])
      ,[PersonenPerSoortUitkeringBijstand] = [PersonenPerSoortUitkeringBijstand_74]
      ,[PersonenPerSoortUitkeringAO] = [PersonenPerSoortUitkeringAO_75]
      ,[PersonenPerSoortUitkeringWW] = [PersonenPerSoortUitkeringWW_76]
      ,[PersonenPerSoortUitkeringAOW] = [PersonenPerSoortUitkeringAOW_77]
      ,[BedrijfsvestigingenTotaal] = [BedrijfsvestigingenTotaal_81]
      ,[ALandbouwBosbouwEnVisserij] = [ALandbouwBosbouwEnVisserij_82]
      ,[BFNijverheidEnEnergie] = [BFNijverheidEnEnergie_83]
      ,[GIHandelEnHoreca] = [GIHandelEnHoreca_84]
      ,[HJVervoerInformatieEnCommunicatie] = [HJVervoerInformatieEnCommunicatie_85]
      ,[KLFinancieleDienstenOnroerendGoed] = [KLFinancieleDienstenOnroerendGoed_86]
      ,[MNZakelijkeDienstverlening] = [MNZakelijkeDienstverlening_87]
      ,[RUCultuurRecreatieOverigeDiensten] = [RUCultuurRecreatieOverigeDiensten_88]
      ,[PersonenautoSTotaal] = [PersonenautoSTotaal_89]
      ,[PersonenautoSJongerDan6Jaar] = null
      ,[PersonenautoS6JaarEnOuder] = null
      ,[PersonenautoSBrandstofBenzine] = [PersonenautoSBrandstofBenzine_90]
      ,[PersonenautoSOverigeBrandstof] = [PersonenautoSOverigeBrandstof_91]
      ,[PersonenautoSPerHuishouden] = iif([PersonenautoSPerHuishouden_92] like '%.%', null, [PersonenautoSPerHuishouden_92])
      ,[PersonenautoSNaarOppervlakte] = [PersonenautoSNaarOppervlakte_93]
      ,[Bedrijfsmotorvoertuigen] = null
      ,[Motorfietsen] = [Motorfietsen_94]
      ,[AfstandTotHuisartsenpraktijk] = [AfstandTotHuisartsenpraktijk_95]
      ,[AfstandTotGroteSupermarkt] = [AfstandTotGroteSupermarkt_96]
      ,[AfstandTotKinderdagverblijf] = [AfstandTotKinderdagverblijf_97]
      ,[AfstandTotSchool] = [AfstandTotSchool_98]
      ,[ScholenBinnen3Km] = [ScholenBinnen3Km_99]
      ,[OppervlakteTotaal] = [OppervlakteTotaal_100]
      ,[OppervlakteLand] = [OppervlakteLand_101]
      ,[OppervlakteWater] = [OppervlakteWater_102]
      ,[MeestVoorkomendePostcode] = [MeestVoorkomendePostcode_103]
      ,[Dekkingspercentage] = [Dekkingspercentage_104]
      ,[MateVanStedelijkheid] = [MateVanStedelijkheid_105]
      ,[Omgevingsadressendichtheid] = [Omgevingsadressendichtheid_106]
      ,[TotaalDiefstalUitWoningSchuurED] = iif([TotaalDiefstalUitWoningSchuurED_78] like '%.%', null, [TotaalDiefstalUitWoningSchuurED_78])
      ,[VernielingMisdrijfTegenOpenbareOrde] = iif([VernielingMisdrijfTegenOpenbareOrde_79] like '%.%', null, [VernielingMisdrijfTegenOpenbareOrde_79])
      ,[GeweldsEnSeksueleMisdrijven] = iif([GeweldsEnSeksueleMisdrijven_80] like '%.%', null, [GeweldsEnSeksueleMisdrijven_80])
  FROM [empire_staedion_data].[bik].[CBS_BuurtGegevens2019] as CBS
  inner join empire_staedion_data.bik.ELS_ClusternummerBuurtCode as ELS on (N'BU' + RIGHT(N'00000000' + CAST(ELS.BuurtCode AS nvarchar), 8)) = CBS.Codering_3
  where CBS.Codering_3 like 'BU%' and CBS.AantalInwoners_5 <> 0

  union all

  SELECT DISTINCT ELS.BuurtCode
	  ,[Jaar] = 2020
      ,[AantalInwoners] = [AantalInwoners_5]
      ,[Mannen] = [Mannen_6]
      ,[Vrouwen] = [Vrouwen_7]
      ,[k_0Tot15Jaar] = [k_0Tot15Jaar_8]
      ,[k_15Tot25Jaar] = [k_15Tot25Jaar_9]
      ,[k_25Tot45Jaar] = [k_25Tot45Jaar_10]
      ,[k_45Tot65Jaar] = [k_45Tot65Jaar_11]
      ,[k_65JaarOfOuder] = [k_65JaarOfOuder_12]
      ,[Ongehuwd] = [Ongehuwd_13]
      ,[Gehuwd] = [Gehuwd_14]
      ,[Gescheiden] = [Gescheiden_15]
      ,[Verweduwd] = [Verweduwd_16]
      ,[WestersTotaal] = [WestersTotaal_17]
      ,[NietWestersTotaal] = [NietWestersTotaal_18]
      ,[Marokko] = [Marokko_19]
      ,[NederlandseAntillenEnAruba] = [NederlandseAntillenEnAruba_20]
      ,[Suriname] = [Suriname_21]
      ,[Turkije] = [Turkije_22]
      ,[OverigNietWesters] = [OverigNietWesters_23]
      ,[GeboorteTotaal] = iif([GeboorteTotaal_24] like '%.%', null, [GeboorteTotaal_24])
      ,[GeboorteRelatief] = iif([GeboorteRelatief_25] like '%.%', null, [GeboorteRelatief_25])
      ,[SterfteTotaal] = iif([SterfteTotaal_26] like '%.%', null, [SterfteTotaal_26])
      ,[SterfteRelatief] = iif([SterfteRelatief_27] like '%.%', null, [SterfteRelatief_27])
      ,[HuishoudensTotaal] = [HuishoudensTotaal_28]
      ,[Eenpersoonshuishoudens] = [Eenpersoonshuishoudens_29]
      ,[HuishoudensZonderKinderen] = [HuishoudensZonderKinderen_30]
      ,[HuishoudensMetKinderen] = [HuishoudensMetKinderen_31]
      ,[GemiddeldeHuishoudensgrootte] = [GemiddeldeHuishoudensgrootte_32]
      ,[Bevolkingsdichtheid] = [Bevolkingsdichtheid_33]
      ,[Woningvoorraad] = iif([Woningvoorraad_34] like '%.%', null, [Woningvoorraad_34])
      ,[GemiddeldeWoningwaarde] = iif([GemiddeldeWoningwaarde_35] like '%.%', null, [GemiddeldeWoningwaarde_35])
      ,[PercentageEengezinswoning] = iif([PercentageEengezinswoning_36] like '%.%', null, [PercentageEengezinswoning_36])
      ,[PercentageMeergezinswoning] = iif([PercentageMeergezinswoning_37] like '%.%', null, [PercentageMeergezinswoning_37])
      ,[PercentageBewoond] = iif([PercentageBewoond_38] like '%.%', null, [PercentageBewoond_38])
      ,[PercentageOnbewoond] = iif([PercentageOnbewoond_39] like '%.%', null, [PercentageOnbewoond_39])
      ,[Koopwoningen] = iif([Koopwoningen_40] like '%.%', null, [Koopwoningen_40])
      ,[HuurwoningenTotaal] = iif([HuurwoningenTotaal_41] like '%.%', null, [HuurwoningenTotaal_41])
      ,[InBezitWoningcorporatie] = iif([InBezitWoningcorporatie_42] like '%.%', null, [InBezitWoningcorporatie_42])
      ,[InBezitOverigeVerhuurders] = iif([InBezitOverigeVerhuurders_43] like '%.%', null, [InBezitOverigeVerhuurders_43])
      ,[EigendomOnbekend] = iif([EigendomOnbekend_44] like '%.%', null, [EigendomOnbekend_44])
      ,[BouwjaarVoor2000] = iif([BouwjaarVoor2000_45] like '%.%', null, [BouwjaarVoor2000_45])
      ,[BouwjaarVanaf2000] = iif([BouwjaarVanaf2000_46] like '%.%', null, [BouwjaarVanaf2000_46])
      ,[GemiddeldElektriciteitsverbruikTotaal] = iif([GemiddeldElektriciteitsverbruikTotaal_47] like '%.%', null, [GemiddeldElektriciteitsverbruikTotaal_47])
      ,[kWhAppartement] = iif([Appartement_48] like '%.%', null, [Appartement_48])
      ,[kWhTussenwoning] = iif([Tussenwoning_49] like '%.%', null, [Tussenwoning_49])
      ,[kWhHoekwoning] = iif([Hoekwoning_50] like '%.%', null, [Hoekwoning_50])
      ,[kWhTweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_51] like '%.%', null, [TweeOnderEenKapWoning_51])
      ,[kWhVrijstaandeWoning] = iif([VrijstaandeWoning_52] like '%.%', null, [VrijstaandeWoning_52])
      ,[kWhHuurwoning] = iif([Huurwoning_53] like '%.%', null, [Huurwoning_53])
      ,[kWhEigenWoning] = iif([EigenWoning_54] like '%.%', null, [EigenWoning_54])
      ,[GemiddeldAardgasverbruikTotaal] = iif([GemiddeldAardgasverbruikTotaal_55] like '%.%', null, [GemiddeldAardgasverbruikTotaal_55])
      ,[m3Appartement] = iif([Appartement_56] like '%.%', null, [Appartement_56])
      ,[m3Tussenwoning] = iif([Tussenwoning_57] like '%.%', null, [Tussenwoning_57])
      ,[m3Hoekwoning] = iif([Hoekwoning_58] like '%.%', null, [Hoekwoning_58])
      ,[m3TweeOnderEenKapWoning] = iif([TweeOnderEenKapWoning_59] like '%.%', null, [TweeOnderEenKapWoning_59])
      ,[m3VrijstaandeWoning] = iif([VrijstaandeWoning_60] like '%.%', null, [VrijstaandeWoning_60])
      ,[m3Huurwoning] = iif([Huurwoning_61] like '%.%', null, [Huurwoning_61])
      ,[m3EigenWoning] = iif([EigenWoning_62] like '%.%', null, [EigenWoning_62])
      ,[PercentageWoningenMetStadsverwarming] = iif([PercentageWoningenMetStadsverwarming_63] like '%.%', null, [PercentageWoningenMetStadsverwarming_63])
      ,[AantalInkomensontvangers] = iif([AantalInkomensontvangers_64] like '%.%', null, [AantalInkomensontvangers_64])
      ,[GemiddeldInkomenPerInkomensontvanger] = iif([GemiddeldInkomenPerInkomensontvanger_65] like '%.%', null, [GemiddeldInkomenPerInkomensontvanger_65])
      ,[GemiddeldInkomenPerInwoner] = iif([GemiddeldInkomenPerInwoner_66] like '%.%', null, [GemiddeldInkomenPerInwoner_66])
      ,[k_40PersonenMetLaagsteInkomen] = iif([k_40PersonenMetLaagsteInkomen_67] like '%.%', null, [k_40PersonenMetLaagsteInkomen_67])
      ,[k_20PersonenMetHoogsteInkomen] = iif([k_20PersonenMetHoogsteInkomen_68] like '%.%', null, [k_20PersonenMetHoogsteInkomen_68])
      ,[Actieven1575Jaar] = iif([Actieven1575Jaar_69] like '%.%', null, [Actieven1575Jaar_69])
      ,[k_40HuishoudensMetLaagsteInkomen] = iif([k_40HuishoudensMetLaagsteInkomen_70] like '%.%', null, [k_40HuishoudensMetLaagsteInkomen_70])
      ,[k_20HuishoudensMetHoogsteInkomen] = iif([k_20HuishoudensMetHoogsteInkomen_71] like '%.%', null, [k_20HuishoudensMetHoogsteInkomen_71])
      ,[HuishoudensMetEenLaagInkomen] = iif([HuishoudensMetEenLaagInkomen_72] like '%.%', null, [HuishoudensMetEenLaagInkomen_72])
      ,[HuishOnderOfRondSociaalMinimum] = iif([HuishOnderOfRondSociaalMinimum_73] like '%.%', null, [HuishOnderOfRondSociaalMinimum_73])
      ,[PersonenPerSoortUitkeringBijstand] = [PersonenPerSoortUitkeringBijstand_74]
      ,[PersonenPerSoortUitkeringAO] = [PersonenPerSoortUitkeringAO_75]
      ,[PersonenPerSoortUitkeringWW] = [PersonenPerSoortUitkeringWW_76]
      ,[PersonenPerSoortUitkeringAOW] = [PersonenPerSoortUitkeringAOW_77]
      ,[BedrijfsvestigingenTotaal] = iif([BedrijfsvestigingenTotaal_78] like '%.%', null, [BedrijfsvestigingenTotaal_78])
      ,[ALandbouwBosbouwEnVisserij] = iif([ALandbouwBosbouwEnVisserij_79] like '%.%', null, [ALandbouwBosbouwEnVisserij_79])
      ,[BFNijverheidEnEnergie] = iif([BFNijverheidEnEnergie_80] like '%.%', null, [BFNijverheidEnEnergie_80])
      ,[GIHandelEnHoreca] = iif([GIHandelEnHoreca_81] like '%.%', null, [GIHandelEnHoreca_81])
      ,[HJVervoerInformatieEnCommunicatie] = iif([HJVervoerInformatieEnCommunicatie_82] like '%.%', null, [HJVervoerInformatieEnCommunicatie_82])
      ,[KLFinancieleDienstenOnroerendGoed] = iif([KLFinancieleDienstenOnroerendGoed_83] like '%.%', null, [KLFinancieleDienstenOnroerendGoed_83])
      ,[MNZakelijkeDienstverlening] = iif([MNZakelijkeDienstverlening_84] like '%.%', null, [MNZakelijkeDienstverlening_84])
      ,[RUCultuurRecreatieOverigeDiensten] = iif([RUCultuurRecreatieOverigeDiensten_85] like '%.%', null, [RUCultuurRecreatieOverigeDiensten_85])
      ,[PersonenautoSTotaal] = [PersonenautoSTotaal_86]
      ,[PersonenautoSJongerDan6Jaar] = null
      ,[PersonenautoS6JaarEnOuder] = null
      ,[PersonenautoSBrandstofBenzine] = [PersonenautoSBrandstofBenzine_87]
      ,[PersonenautoSOverigeBrandstof] = [PersonenautoSOverigeBrandstof_88]
      ,[PersonenautoSPerHuishouden] = iif([PersonenautoSPerHuishouden_89] like '%.%', null, [PersonenautoSPerHuishouden_89])
      ,[PersonenautoSNaarOppervlakte] = [PersonenautoSNaarOppervlakte_90]
      ,[Bedrijfsmotorvoertuigen] = null
      ,[Motorfietsen] = [Motorfietsen_91]
      ,[AfstandTotHuisartsenpraktijk] = iif([AfstandTotHuisartsenpraktijk_92] like '%.%', null, [AfstandTotHuisartsenpraktijk_92])
      ,[AfstandTotGroteSupermarkt] = iif([AfstandTotGroteSupermarkt_93] like '%.%', null, [AfstandTotGroteSupermarkt_93])
      ,[AfstandTotKinderdagverblijf] = iif([AfstandTotKinderdagverblijf_94] like '%.%', null, [AfstandTotKinderdagverblijf_94])
      ,[AfstandTotSchool] = iif([AfstandTotSchool_95] like '%.%', null, [AfstandTotSchool_95])
      ,[ScholenBinnen3Km] = iif([ScholenBinnen3Km_96] like '%.%', null, [ScholenBinnen3Km_96])
      ,[OppervlakteTotaal] = [OppervlakteTotaal_97]
      ,[OppervlakteLand] = [OppervlakteLand_98]
      ,[OppervlakteWater] = [OppervlakteWater_99]
      ,[MeestVoorkomendePostcode] = [MeestVoorkomendePostcode_100]
      ,[Dekkingspercentage] = [Dekkingspercentage_101]
      ,[MateVanStedelijkheid] = [MateVanStedelijkheid_102]
      ,[Omgevingsadressendichtheid] = [Omgevingsadressendichtheid_103]
      ,[TotaalDiefstalUitWoningSchuurED] = null
      ,[VernielingMisdrijfTegenOpenbareOrde] = null
      ,[GeweldsEnSeksueleMisdrijven] = null
  FROM [empire_staedion_data].[bik].[CBS_BuurtGegevens2020] as CBS
  inner join empire_staedion_data.bik.ELS_ClusternummerBuurtCode as ELS on (N'BU' + RIGHT(N'00000000' + CAST(ELS.BuurtCode AS nvarchar), 8)) = CBS.Codering_3
  where CBS.Codering_3 like 'BU%' and CBS.AantalInwoners_5 <> 0
GO
