SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE view [Liqprog].[Projectgegevens]
as
select 
  [Datum bijgewerkt]                              = nullif(convert(date,convert(datetime,[BIJWERKDATUM])),'1900-01-01'),
  [Projectnummer]                                 = [PROJECTNUMMER],
  [Projectnaam]                                   = [PROJECTNAAM],
  [Projectsoort]                                  = [PROJECTSOORT],
  [Status]                                        = [STATUS_STAAT_OP],
  [THUISTEAMMANAGER]                              = [THUISTEAMMANAGER],
  [Assetmanager]                                  = [ASSETMANAGER_(GEBIED)],
  [Projectmanager]                                = [PROJECTMANAGER],
  [Aannemer]                                      = [AANNEMER],
  [Aanbestedingsvorm]                             = [AANBESTEDINGSVORM],
  [Projectfase]                                   = [PROJECTFASE],
  [Datum startdocument MJIR]                      = nullif(convert(date,convert(datetime,[STARTDOCUMENT_MJIR])),'1900-01-01'),
  [Datum projectbesluit MJIR]                     = nullif(convert(date,convert(datetime,[PROJECTBESLUIT_MJIR])),'1900-01-01'),
  [Datum aquisitie ontwikkelbesluit MJIR]         = nullif(convert(date,convert(datetime,[ACQUISITIE_ONTWIKKELBESLUIT_MJIR])),'1900-01-01'),
  [Datum investeringsbesluit MJIR]                = nullif(convert(date,convert(datetime,[INVESTERINGSBESLUIT_MJIR])),'1900-01-01'),
  [Datum aankoop uitvoeringsbesluit MJIR]         = nullif(convert(date,convert(datetime,[AANKOOP_UITVOERINGSBESLUIT_MJIR])),'1900-01-01'),
  [Datum dechargebesluit MJIR]                    = nullif(convert(date,convert(datetime,[DECHARGEBESLUIT_MJIR])),'1900-01-01'),
  [Datum intentieovereenkomst MJIR]               = nullif(convert(date,convert(datetime,[INTENTIEOVEREENKOMST_MJIR])),'1900-01-01'),
  [Datum samenwerkingsovereenkomst MJIR]          = nullif(convert(date,convert(datetime,[SAMENWERKINGSOVEREENKOMST_MJIR])),'1900-01-01'),
  [Datum prestatieovereenkomst MJIR]              = nullif(convert(date,convert(datetime,[PRESTATIEOVEREENKOMST_MJIR])),'1900-01-01'),
  [Datum bouwteamovereenkomst MJIR]               = nullif(convert(date,convert(datetime,[BOUWTEAMOVEREENKOMST_MJIR])),'1900-01-01'),
  [Datum turnkey overeenkomst MJIR]               = nullif(convert(date,convert(datetime,[TURN_KEY_OVEREENKOMST_MJIR])),'1900-01-01'),
  [Datum aannemingsovereenkomst MJIR]             = nullif(convert(date,convert(datetime,[AANNEMINGSOVEREENKOMST_MJIR])),'1900-01-01'),
  [Datum oplevering MJIR]                         = nullif(convert(date,convert(datetime,[OPLEVERING_MJIR])),'1900-01-01'),
  [Datum startdocument PROG]                      = nullif(convert(date,convert(datetime,[STARTDOCUMENT_PROG])),'1900-01-01'),
  [Datum projectbesluit PROG]                     = nullif(convert(date,convert(datetime,[PROJECTBESLUIT_PROG])),'1900-01-01'),
  [Datum aquisitie ontwikkelbesluit PROG]         = nullif(convert(date,convert(datetime,[ACQUISITIE_ONTWIKKELBESLUIT_PROG])),'1900-01-01'),
  [Datum investeringsbesluit PROG]                = nullif(convert(date,convert(datetime,[INVESTERINGSBESLUIT_PROG])),'1900-01-01'),
  [Datum aankoop uitvoeringsbesluit PROG]         = nullif(convert(date,convert(datetime,[AANKOOP_UITVOERINGSBESLUIT_PROG])),'1900-01-01'),
  [Datum dechargebesluit PROG]                    = nullif(convert(date,convert(datetime,[DECHARGEBESLUIT_PROG])),'1900-01-01'),
  [Datum intentieovereenkomst PROG]               = nullif(convert(date,convert(datetime,[INTENTIEOVEREENKOMST_PROG])),'1900-01-01'),
  [Datum samenwerkingsovereenkomst PROG]          = nullif(convert(date,convert(datetime,[SAMENWERKINGSOVEREENKOMST_PROG])),'1900-01-01'),
  [Datum prestatieovereenkomst PROG]              = nullif(convert(date,convert(datetime,[PRESTATIEOVEREENKOMST_PROG])),'1900-01-01'),
  [Datum bouwteamovereenkomst PROG]               = nullif(convert(date,convert(datetime,[BOUWTEAMOVEREENKOMST_PROG])),'1900-01-01'),
  [Datum turnkey overeenkomst PROG]               = nullif(convert(date,convert(datetime,[TURN_KEY_OVEREENKOMST_PROG])),'1900-01-01'),
  [Datum aannemingsovereenkomst PROG]             = nullif(convert(date,convert(datetime,[AANNEMINGSOVEREENKOMST_PROG])),'1900-01-01'),
  [Datum oplevering PROG]                         = nullif(convert(date,convert(datetime,[OPLEVERING_PROG])),'1900-01-01'),
  [Datum start sloop MJIR]                        = nullif(convert(date,convert(datetime,[START_SLOOP_MJIR])),'1900-01-01'),
  [Datum start bouw MJIR]                         = nullif(convert(date,convert(datetime,[START_BOUW_MJIR])),'1900-01-01'),
  [Datum programma nieuwbouw MJIR]                = nullif(convert(date,convert(datetime,[PROGRAMMA_NIEUWBOUW_MJIR])),'1900-01-01'),
  [Datum programma renovatie MJIR]                = nullif(convert(date,convert(datetime,[PROGRAMMA_RENOVATIE_MJIR])),'1900-01-01'),
  [Datum programma transformatie MJIR]            = nullif(convert(date,convert(datetime,[PROGRAMMA_TRANSFORMATIE_MJIR])),'1900-01-01'),
  [Datum programma sloop MJIR]                    = nullif(convert(date,convert(datetime,[PROGRAMMA_SLOOP_MJIR])),'1900-01-01'),
  [Datum omgevingsvergunning MJIR]                = nullif(convert(date,convert(datetime,[OMGEVINGSVERGUNNING_MJIR])),'1900-01-01'),
  [Datum start werkzaamheden MJIR]                = nullif(convert(date,convert(datetime,[START_WERKZAAMHEDEN_MJIR])),'1900-01-01'),
  [Datum start sloop PROG]                        = nullif(convert(date,convert(datetime,[START_SLOOP_PROG])),'1900-01-01'),
  [Datum start bouw PROG]                         = nullif(convert(date,convert(datetime,[START_BOUW_PROG])),'1900-01-01'),
  [Datum programma nieuwe PROG]                   = nullif(convert(date,convert(datetime,[PROGRAMMA_NIEUWBOUW_PROG])),'1900-01-01'),
  [Datum programma renovatie PROG]                = nullif(convert(date,convert(datetime,[PROGRAMMA_RENOVATIE_PROG])),'1900-01-01'),
  [Datum programma transformatie PROG]            = nullif(convert(date,convert(datetime,[PROGRAMMA_TRANSFORMATIE_PROG])),'1900-01-01'),
  [Datum programma sloop PROG]                    = nullif(convert(date,convert(datetime,[PROGRAMMA_SLOOP_PROG])),'1900-01-01'),
  [Datum omgevingsvergunning PROG]                = nullif(convert(date,convert(datetime,[OMGEVINGSVERGUNNING_PROG])),'1900-01-01'),
  [Datum start werkzaamheden PROG]                = nullif(convert(date,convert(datetime,[START_WERKZAAMHEDEN_PROG])),'1900-01-01'),
  [Bedrag project budget]                         = [PROJECT_BUDGET],
  [Bedrag project prognose]                       = [PROJECT_PROGNOSE],
  [Bedrag project gerealiseerd]                   = 0.00000,
  [LQ_MND_1]                                      = [LQ_JAN],
  [LQ_MND_2]                                      = [LQ_FEB],
  [LQ_MND_3]                                      = [LQ_MRT],
  [LQ_MND_4]                                      = [LQ_APR],
  [LQ_MND_5]                                      = [LQ_MEI],
  [LQ_MND_6]                                      = [LQ_JUN],
  [LQ_MND_7]                                      = [LQ_JUL],
  [LQ_MND_8]                                      = [LQ_AUG],
  [LQ_MND_9]                                      = [LQ_SEP],
  [LQ_MND_10]                                     = [LQ_OKT],
  [LQ_MND_11]                                     = [LQ_NOV],
  [LQ_MND_12]                                     = [LQ_DEC],
  [JAAR_1]                                        = [JAAR_01],
  [JAAR_2]                                        = [JAAR_02],
  [JAAR_3]                                        = [JAAR_03],
  [JAAR_4]                                        = [JAAR_04],
  [JAAR_5]                                        = [JAAR_05],
  [JAAR_6]                                        = [JAAR_06],
  [JAAR_7]                                        = [JAAR_07],
  [JAAR_8]                                        = [JAAR_08],
  [JAAR_9]                                        = [JAAR_09],
  [JAAR_10]                                       = [JAAR_10],
  [JAAR_11]                                       = [JAAR_11],
  [JAAR_12]                                       = [JAAR_12],
  [JAAR_13]                                       = [JAAR_13],
  [JAAR_14]                                       = [JAAR_14],
  [JAAR_15]                                       = [JAAR_15]
from [empire_staedion_data].[dbo].[gotikr_data]
GO
