CREATE TABLE [Algemeen].[Eenheid]
(
[Sleutel] [int] NOT NULL,
[Eenheidnummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Eenheid] [nvarchar] (113) COLLATE Latin1_General_CI_AS NULL,
[Adres] [nvarchar] (92) COLLATE Latin1_General_CI_AS NULL,
[Plaats] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Wijk] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[Buurt] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Gemeente] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Gemeente code] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Straatnaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Huisnummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Toevoegsel] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Postcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Bouwjaar] [int] NULL,
[Renovatiejaar] [int] NULL,
[Gerenoveerd] [varchar] (16) COLLATE Latin1_General_CI_AS NOT NULL,
[Bouw/renovatiejaar] [int] NULL,
[Klasse bouw/renovatiejaar] [varchar] (22) COLLATE Latin1_General_CI_AS NOT NULL,
[Klasse bouw/renovatiejaar sortering] [int] NOT NULL,
[Klasse bouwjaar] [varchar] (22) COLLATE Latin1_General_CI_AS NOT NULL,
[Klasse bouwjaar sortering] [int] NOT NULL,
[Klasse renovatiejaar] [varchar] (22) COLLATE Latin1_General_CI_AS NOT NULL,
[Klasse renovatiejaar sortering] [int] NOT NULL,
[Bouwblok] [varchar] (71) COLLATE Latin1_General_CI_AS NULL,
[Bouwbloknummer] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Bouwbloknaam] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[FT-Cluster] [varchar] (71) COLLATE Latin1_General_CI_AS NULL,
[FT-Clusternummer] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[FT-Clusternaam] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[VVE-Cluster] [varchar] (71) COLLATE Latin1_General_CI_AS NULL,
[VVE-Clusternummer] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[VVE-Clusternaam] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[Eenheidtype Corpodata] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Eenheidtype groepering] [varchar] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[Eenheidtype groepering sortering] [int] NOT NULL,
[Technische type omschrijving] [nvarchar] (70) COLLATE Latin1_General_CI_AS NULL,
[Vastgoedtype] [varchar] (23) COLLATE Latin1_General_CI_AS NULL,
[Lift] [tinyint] NULL,
[Etage] [varchar] (22) COLLATE Latin1_General_CI_AS NULL,
[Aantal kamers] [int] NULL,
[Groepering aantal kamers] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[Gem. oppervlakte] [numeric] (38, 20) NULL,
[Oppervlakte] [numeric] (38, 20) NULL,
[Leegwaarde] [float] NULL,
[Marktwaarde] [float] NULL,
[Beleidswaarde] [decimal] (12, 2) NULL,
[Peildatum waarden] [date] NULL,
[Assetmanager] [nvarchar] (92) COLLATE Latin1_General_CI_AS NULL,
[Verhuurteam] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Bedrijf] [varchar] (29) COLLATE Latin1_General_CI_AS NOT NULL,
[Juridisch eigenaar] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[In exploitatie] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Einde exploitatie] [datetime] NOT NULL,
[Reden in exploitatie] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[Reden uit exploitatie] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[Is OGEH] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Huidige labelconditie] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Status eenheid] [varchar] (15) COLLATE Latin1_General_CI_AS NULL,
[Status VvE] [varchar] (7) COLLATE Latin1_General_CI_AS NULL,
[Datum in exploitatie] [datetime] NOT NULL,
[Datum in exploitatie gevuld] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Streefhuur] [decimal] (38, 20) NULL,
[Maximale huur] [decimal] (38, 20) NULL,
[Markthuur] [float] NULL,
[Kalehuur] [numeric] (12, 2) NULL,
[Sleutel huurklasse obv kalehuur] [int] NULL,
[Huurklasse 2 obv kalehuur] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[Huurklasse 2 obv kalehuur sort] [int] NULL,
[Huurklasse obv streefhuur] [varchar] (27) COLLATE Latin1_General_CI_AS NULL,
[Huurklasse obv streefhuur sort] [int] NULL,
[Huurklasse obv kalehuur] [varchar] (27) COLLATE Latin1_General_CI_AS NULL,
[Huurklasse obv kalehuur sort] [int] NULL,
[Huurklasse obv subsidiabel] [varchar] (27) COLLATE Latin1_General_CI_AS NULL,
[Huurklasse obv subsidiabel sort] [int] NULL,
[DAEB] [varchar] (9) COLLATE Latin1_General_CI_AS NOT NULL,
[Doelgroep] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Streefhuursegmentatie] [varchar] (23) COLLATE Latin1_General_CI_AS NOT NULL,
[Streefhuursegmentatie sortering] [int] NOT NULL,
[Voorheen Vestia] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Huidig contract met reden huurverlaging] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[EAN Code Electriciteit] [nvarchar] (18) COLLATE Latin1_General_CI_AS NOT NULL,
[EAN Code Gas] [nvarchar] (18) COLLATE Latin1_General_CI_AS NOT NULL,
[Contactpersoon BOG] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
