CREATE TABLE [Algemeen].[Tijd]
(
[id] [int] NOT NULL,
[datum] [date] NULL,
[day] [smallint] NOT NULL,
[weekday] [smallint] NOT NULL,
[weekday_name] [varchar] (25) COLLATE Latin1_General_CI_AS NOT NULL,
[isoweek] [int] NOT NULL,
[month] [smallint] NOT NULL,
[month_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NOT NULL,
[month_name_long] [varchar] (25) COLLATE Latin1_General_CI_AS NOT NULL,
[quarter] [smallint] NOT NULL,
[tertile] [smallint] NOT NULL,
[yearhalf] [smallint] NOT NULL,
[year] [smallint] NOT NULL,
[day_relative] [int] NULL,
[month_relative] [int] NULL,
[quarter_relative] [int] NULL,
[tertile_relative] [smallint] NULL,
[yearhalf_relative] [smallint] NULL,
[year_relative] [smallint] NULL,
[last_loading_day] [bit] NULL,
[datestr] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[monthstr] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[yearmonthstr] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[isoweeknum] [int] NULL,
[isoweekyear] [smallint] NULL,
[month_key] [int] NULL,
[quarter_key] [int] NULL,
[quarterstr] [varchar] (9) COLLATE Latin1_General_CI_AS NULL,
[tertile_key] [int] NULL,
[tertilestr] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[tertilestr_short] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[isoweekstr] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[periodid] [varchar] (21) COLLATE Latin1_General_CI_AS NOT NULL,
[datum_name_long] [varchar] (33) COLLATE Latin1_General_CI_AS NULL,
[datum_name] [varchar] (33) COLLATE Latin1_General_CI_AS NULL,
[datum_name_short] [varchar] (33) COLLATE Latin1_General_CI_AS NULL,
[datum_value] [date] NULL,
[datum_sortorder] [int] NULL,
[jaar] [smallint] NULL,
[jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[jaar_value] [smallint] NULL,
[jaar_sortorder] [smallint] NULL,
[half_jaar] [int] NULL,
[half_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[half_jaar_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[half_jaar_value] [smallint] NULL,
[half_jaar_sortorder] [int] NULL,
[tertaal] [int] NULL,
[tertaal_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[tertaal_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[tertaal_value] [smallint] NULL,
[tertaal_sortorder] [int] NULL,
[kwartaal] [int] NULL,
[kwartaal_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[kwartaal_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[kwartaal_value] [smallint] NULL,
[kwartaal_sortorder] [int] NULL,
[maand] [int] NULL,
[maand_name] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[maand_name_short] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[maand_value] [smallint] NULL,
[maand_sortorder] [int] NULL,
[weekjaar] [smallint] NULL,
[weekjaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[weekjaar_value] [smallint] NULL,
[weekjaar_sortorder] [smallint] NULL,
[week] [int] NULL,
[week_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[week_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[week_value] [smallint] NULL,
[week_sortorder] [int] NULL,
[helft_vh_jaar] [smallint] NULL,
[helft_vh_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[helft_vh_jaar_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[helft_vh_jaar_value] [smallint] NULL,
[helft_vh_jaar_sortorder] [smallint] NULL,
[tertaal_vh_jaar] [smallint] NULL,
[tertaal_vh_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[tertaal_vh_jaar_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[tertaal_vh_jaar_value] [smallint] NULL,
[tertaal_vh_jaar_sortorder] [smallint] NULL,
[kwartaal_vh_jaar] [smallint] NULL,
[kwartaal_vh_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[kwartaal_vh_jaar_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[kwartaal_vh_jaar_value] [smallint] NULL,
[kwartaal_vh_jaar_sortorder] [smallint] NULL,
[maand_vh_jaar] [smallint] NULL,
[maand_vh_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[maand_vh_jaar_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[maand_vh_jaar_name_letter] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[maand_vh_jaar_value] [smallint] NULL,
[maand_vh_jaar_sortorder] [smallint] NULL,
[week_vh_jaar] [smallint] NULL,
[week_vh_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[week_vh_jaar_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[week_vh_jaar_value] [smallint] NULL,
[week_vh_jaar_sortorder] [smallint] NULL,
[dag_vh_jaar] [smallint] NULL,
[dag_vh_jaar_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[dag_vh_jaar_value] [smallint] NULL,
[dag_vh_jaar_sortorder] [smallint] NULL,
[dag_vd_maand] [smallint] NULL,
[dag_vd_maand_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[dag_vd_maand_value] [smallint] NULL,
[dag_vd_maand_sortorder] [smallint] NULL,
[dag_vd_week] [smallint] NULL,
[dag_vd_week_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[dag_vd_week_name_short] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[dag_vd_week_name_letter] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[dag_vd_week_value] [smallint] NULL,
[dag_vd_week_sortorder] [smallint] NULL,
[jaar_relatief] [smallint] NULL,
[jaar_relatief_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[jaar_relatief_value] [smallint] NULL,
[jaar_relatief_sortorder] [smallint] NULL,
[half_jaar_relatief] [smallint] NULL,
[half_jaar_relatief_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[half_jaar_relatief_value] [smallint] NULL,
[half_jaar_relatief_sortorder] [smallint] NULL,
[tertaal_relatief] [smallint] NULL,
[tertaal_relatief_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[tertaal_relatief_value] [smallint] NULL,
[tertaal_relatief_sortorder] [smallint] NULL,
[kwartaal_relatief] [int] NULL,
[kwartaal_relatief_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[kwartaal_relatief_value] [int] NULL,
[kwartaal_relatief_sortorder] [int] NULL,
[maand_relatief] [int] NULL,
[maand_relatief_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[maand_relatief_value] [int] NULL,
[maand_relatief_sortorder] [int] NULL,
[dag_relatief] [int] NULL,
[dag_relatief_name] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[dag_relatief_value] [int] NULL,
[dag_relatief_sortorder] [int] NULL,
[staedion_rapportage_key] [smallint] NULL,
[staedion_rapportage_str] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[staedion_kwartaal_name_short] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
