CREATE TABLE [Casix].[Werkopdracht]
(
[ID] [bigint] NULL,
[Opdrachtnummer] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Opdrachtdatum] [datetime2] (0) NULL,
[Omschrijving] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[AdresVolledig] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[HuurderNaam] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[HuurderEmail] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[HuurderTelefoon] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[HuurderMobiel] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[VroegsteStart] [datetime2] (0) NULL,
[UiterlijkGereed] [datetime2] (0) NULL,
[PlanningVoorkeur] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[PlanningAanvang] [datetime2] (0) NULL,
[TijdsduurUren] [float] NULL,
[PlanningEinde] [datetime2] (0) NULL,
[Latitude] [float] NULL,
[Longitude] [float] NULL,
[BedragReservering] [float] NULL,
[Bedrag] [float] NULL,
[RedenAfwijzing] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Status] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[AcceptatieAdvies] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[OuderdomDagen] [bigint] NULL,
[ExternID] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ExternLaatsteSync] [datetime2] (0) NULL,
[EindeUitvoering] [datetime2] (0) NULL,
[StartUitvoering] [datetime2] (0) NULL,
[Werkopdracht_Aannemer] [bigint] NULL,
[Werkopdracht_Inkoopopdracht] [bigint] NULL,
[Werkopdracht_AannemerMedewerker] [bigint] NULL,
[Werkopdracht_Verblijfsobject] [bigint] NULL,
[Werkopdracht_Opname] [bigint] NULL,
[Werkopdracht_Reparatieverzoek] [bigint] NULL,
[Werkopdracht_Onderhoudsurgentie] [bigint] NULL,
[Werkopdracht_Onderhoudssjabloon] [bigint] NULL,
[Werkopdracht_Onderhoudsverzoek] [bigint] NULL,
[PlafondbedragAutomatischeAcceptatie] [float] NULL,
[AfspraakStartVroegstActueel] [datetime2] (0) NULL,
[AfspraakStartLaatstActueel] [datetime2] (0) NULL,
[Werkopdracht_GebruikerOpzichter] [bigint] NULL,
[changedDate] [datetime2] (0) NULL
) ON [PRIMARY]
GO
