CREATE TABLE [Contact].[Leverancier]
(
[leverancier_id] [int] NOT NULL IDENTITY(1, 1),
[Ingangsdatum] [date] NULL,
[Einddatum] [date] NULL,
[Ingevoerd op] [datetime] NULL,
[Ingevoerd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Geblokkeerd op] [datetime] NULL,
[Geblokkeerd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Timestamp] [varbinary] (8) NULL,
[No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Naam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Naam 2] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Naam 3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Adres] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Adres 2] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Postcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Plaats] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Land] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Relatienr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Primair relatienr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Contactpersoon] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Telefoonnummer] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Telefoon overdag] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Telefoon 3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Telefoon 4] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Telefoon 5] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Mobiel] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Mobiel 2] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Mobiel 3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Mobiel 4] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Mobiel 5] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[E-Mail] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[E-mail adres tbv orders] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[E-mail 3] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[E-mail 4] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[E-mail 5] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Fax nr] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Website] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Dimensiewaarde 1_id] [int] NULL,
[Leveranciersboekingsgroep_id] [int] NULL,
[Betalingsconditie_id] [int] NULL,
[Verzendwijze_id] [int] NULL,
[Geblokkeerd] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[BTW nummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[KvK nummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Inkoper] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Inkoper naam] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Betalingswijze_id] [int] NULL,
[Bedrijfsboekingsgroep_id] [int] NULL,
[Datum laatste wijziging] [date] NULL,
[Vereffeningswijze] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Prijzen inclusief btw] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Nummerreeks] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Belastingplichtig] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Partnersoort] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Leverancierbankrekening_id] [int] NULL,
[Oud nummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Soort] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Bedrijfsvereniging] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Aansluitingsnr Bedrijfsvereniging] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Loonbelastingnr] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Verklaring Belastingdienst dd] [date] NULL,
[Verklaring Bedrijfsvereniging dd] [date] NULL,
[ZZP-verklaring dd] [date] NULL,
[Transactiewijze_id] [int] NULL,
[Leveranciersoort] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Opslag] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toon orders <Wacht op goedkeuring>] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Gereedmelden vanuit portal] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toon inkooporders] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toon DO orders] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toon PO orders] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toon project orders] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inkoopwerkwijze_id] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Wijzigen G rekening vanuit portal] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Automatisch boeken] [nchar] (3) COLLATE Latin1_General_CI_AS NULL,
[RSIN nr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Spendcategorie] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Groslijst] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Contracten] [int] NULL,
[Laatste omzet] [date] NULL
) ON [PRIMARY]
GO
