CREATE TABLE [Dashboard].[Indicator]
(
[id] [int] NOT NULL,
[parent_id] [int] NULL,
[Omschrijving] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[fk_indicatorgroep_id] [int] NULL,
[fk_kpilevel_id] [int] NULL,
[Aanduiding] [nvarchar] (8) COLLATE Latin1_General_CI_AS NULL,
[Volgorde] [int] NULL,
[Zichtbaar] [bit] NULL CONSTRAINT [DF_Indicator_indicator_zichtbaar] DEFAULT ((0)),
[fk_kleurschema_id] [int] NULL,
[Grenswaarde_1] [numeric] (12, 2) NULL,
[Grenswaarde_2] [numeric] (12, 2) NULL,
[Grenswaarde_3] [numeric] (12, 2) NULL,
[fk_bedrijfsonderdeel_id] [int] NULL,
[fk_aanspreekpunt_id] [int] NULL,
[fk_wijzevullen_id] [int] NULL,
[Marge_percentage] [numeric] (12, 2) NULL,
[fk_schaalsoort_id] [int] NULL,
[fk_veldtype_id] [int] NULL,
[Url] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Gecontroleerd] [smallint] NULL,
[fk_subsysteem_id] [int] NULL,
[Jaarnorm] [numeric] (12, 4) NULL,
[Weergaveformat] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[fk_bron_id] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[fk_proces_id] [int] NULL,
[Definitie] [nvarchar] (1024) COLLATE Latin1_General_CI_AS NULL,
[Cumulatief] [bit] NULL,
[Gemiddelde] [int] NULL,
[Observatie] [bit] NULL CONSTRAINT [DF_Indicator_Observatie] DEFAULT ((0)),
[Detailrapport] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[procedure_actief] [bit] NULL,
[procedure_naam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[procedure_argument] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[procedure_opmerking] [ntext] COLLATE Latin1_General_CI_AS NULL,
[fk_berekeningswijze_id] [int] NULL,
[fk_frequentie_id] [int] NULL,
[controle_brontabel] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Details] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [Dashboard].[Indicator] ADD CONSTRAINT [PK__Indicato__3213E83FEE4D6445] PRIMARY KEY CLUSTERED ([id]) ON [PRIMARY]
GO
