CREATE TABLE [DatabaseBeheer].[VerwerkingSQLAgentJobs]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[omgeving] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Jobnaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Datum] [datetime] NULL,
[Begintijd] [datetime] NULL,
[Eindtijd] [datetime] NULL,
[Duur] [datetime] NULL,
[Jobstatus] [tinyint] NULL,
[Server] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Bron] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DWH_versie_empire] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DWH_versie_ETL] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DWH_versie_maatwerk] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Versie_Empire] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Aantal_perioden] [int] NULL,
[kopieren_data_status] [tinyint] NULL,
[Start_kopieren_data] [datetime] NULL,
[Einde_kopieren_data] [datetime] NULL,
[Duur_stap_kopieren] [datetime] NULL,
[Verwerken_data_status] [tinyint] NULL,
[Begin_verwerken_data] [datetime] NULL,
[Einde_verwerken_data] [datetime] NULL,
[Duur_verwerken_data] [datetime] NULL,
[Tijdelijke_correctie_status] [tinyint] NULL,
[Begin_tijdelijke_correctie] [datetime] NULL,
[Einde_tijdelijke_correctie] [datetime] NULL,
[Duur_tijdelijke_correctie] [datetime] NULL,
[Process_status] [tinyint] NULL,
[Begin_process] [datetime] NULL,
[Einde_process] [datetime] NULL,
[Duur_process] [datetime] NULL,
[ETL_tijdig] [tinyint] NULL,
[ETL_ok] [tinyint] NULL,
[Processen_ok] [tinyint] NULL,
[Opmerking_ETL] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Opmerking_OLAP] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
