CREATE TABLE [Eenheden].[Eigenschappen]
(
[Eigenschappen_id] [int] NOT NULL IDENTITY(1, 1),
[Bedrijf_id] [int] NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Ingangsdatum] [date] NULL,
[Einddatum] [date] NULL,
[Straatnaam] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Huisnummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Huisnummer toevoeging] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Postcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Plaats] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Gemeente] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Wijk Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Wijk] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[CBS buurt] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Buurt] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CBS Wijk Code] [nvarchar] (6) COLLATE Latin1_General_CI_AS NULL,
[CBS Buurt Code] [nvarchar] (8) COLLATE Latin1_General_CI_AS NULL,
[Betreft] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Eenheidstatus_id] [int] NULL,
[Datum in exploitatie] [date] NULL,
[Reden in exploitatie] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[Datum uit exploitatie] [date] NULL,
[Reden uit exploitatie] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[BAG verblijfsobject] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[BAG pand] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[BAG straatnaam] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[BAG huisnummer] [int] NULL,
[BAG huisnummer toevoeging] [nvarchar] (4) COLLATE Latin1_General_CI_AS NULL,
[BAG huisnummer letter] [nchar] (1) COLLATE Latin1_General_CI_AS NULL,
[BAG postcode] [nvarchar] (6) COLLATE Latin1_General_CI_AS NULL,
[BAG plaats] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[BAG bouwjaar] [int] NULL,
[Doelgroep] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Huurbeleid] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Huidige labelconditie] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[OGE type] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[Cluster type] [nvarchar] (25) COLLATE Latin1_General_CI_AS NULL,
[FT clusternr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[FT clusternaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Financieel clusternr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Financieel clusternaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Bouwbloknr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Bouwbloknaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Vve clusternr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[VvE clusternaam] [nvarchar] (110) COLLATE Latin1_General_CI_AS NULL,
[Status VVE] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[VvE (code) Extern] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[VvE Beheerder] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Jaar laatste renovatie] [int] NULL,
[Assetmanager] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Contactpersoon VvE] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Vertegenwoordiger VvE] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Thuisteam] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Verhuurteam] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte BAG] [decimal] (12, 2) NULL,
[Woonruimte] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[Type monument] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Rijksbeschermd stadsgezicht] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Gemeentelijk beschermd stadsgezicht] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Studentenwoning] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Corpodatatype_id] [int] NULL,
[Technisch type_id] [int] NULL,
[Adres] AS (((([Straatnaam]+' ')+[Huisnummer])+' ')+[Huisnummer toevoeging]),
[Eenheid + adres] AS (((((([Eenheidnr]+' ')+[Straatnaam])+' ')+[Huisnummer])+' ')+[Huisnummer toevoeging]),
[Doelgroep_id] [smallint] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Egenschappen_01] ON [Eenheden].[Eigenschappen] ([Bedrijf_id], [Eenheidnr], [Ingangsdatum]) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [Eigenschappen_pk] ON [Eenheden].[Eigenschappen] ([Eigenschappen_id]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Eigenschappen_02] ON [Eenheden].[Eigenschappen] ([Einddatum]) INCLUDE ([Eenheidnr], [Eenheid + adres]) ON [PRIMARY]
GO
