CREATE TABLE [Eenheden].[Meetwaarden]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[Peildatum] [date] NULL,
[Bedrijf_id] [int] NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Eigenschappen_id] [int] NULL,
[Woningwaardering_id] [int] NULL,
[Exploitatiestatus_id] [int] NULL,
[Eenheidstatus_id] [int] NULL,
[Verhuurbare dagen] [int] NULL,
[Huurdernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Prolongatietermijn] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Kale huur] [decimal] (12, 2) NULL,
[Kale huur incl. btw] [decimal] (12, 2) NULL,
[Netto huur] [decimal] (12, 2) NULL,
[Netto huur incl. btw] [decimal] (12, 2) NULL,
[Btw op netto huur] [char] (3) COLLATE Latin1_General_CI_AS NULL,
[Huurkorting] [decimal] (12, 2) NULL,
[Huurkorting incl. btw] [decimal] (12, 2) NULL,
[Netto huur incl. korting en btw] [decimal] (12, 2) NULL,
[Btw compensatie] [decimal] (12, 2) NULL,
[Btw compensatie incl. btw] [decimal] (12, 2) NULL,
[Verbruikskosten] [decimal] (12, 2) NULL,
[Verbruikskosten incl. btw] [decimal] (12, 2) NULL,
[Servicekosten] [decimal] (12, 2) NULL,
[Service- en verbruikkosten] [decimal] (12, 2) NULL,
[Servicekosten incl. btw] [decimal] (12, 2) NULL,
[Stookkosten] [decimal] (12, 2) NULL,
[Water] [decimal] (12, 2) NULL,
[Water incl. btw] [decimal] (12, 2) NULL,
[Bruto huur] [decimal] (12, 2) NULL,
[Bruto huur incl. btw] [decimal] (12, 2) NULL,
[Subsidiabel deel] [decimal] (12, 2) NULL,
[Subsidiabele huur] [decimal] (12, 2) NULL,
[Markthuur] [decimal] (12, 2) NULL,
[Maximaal toegestane huur] [decimal] (12, 2) NULL,
[Percentage max. redelijke huur] [decimal] (12, 2) NULL,
[Aftopgrens] [decimal] (12, 2) NULL,
[Streefhuur] [decimal] (12, 2) NULL,
[Administratief eigenaar] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Juridisch eigenaar] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Beheerder] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Mutatiehuur] [decimal] (12, 2) NULL,
[Subsidiabele energiekosten afgetopt] [decimal] (12, 2) NULL,
[Subsidiabele schoonmaakkosten afgetopt] [decimal] (12, 2) NULL,
[Subsidiabele huismeesterkosten afgetopt] [decimal] (12, 2) NULL,
[Subsidiabele kapitaal/onderhoudskosten afgetopt] [decimal] (12, 2) NULL,
[Subsidiabele energiekosten] [decimal] (12, 2) NULL,
[Subsidiabele schoonmaakkosten] [decimal] (12, 2) NULL,
[Subsidiabele huismeesterkosten] [decimal] (12, 2) NULL,
[Subsidiabele kapitaal/onderhoudskosten] [decimal] (12, 2) NULL,
[Aantal sterren toegankelijkheid] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Keuken] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Verdieping (WBS)] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Verwarming] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Zolder] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Lift] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte Woonkamer (WBS)] [decimal] (12, 2) NULL,
[Oppervlakte Keuken (WBS)] [decimal] (12, 2) NULL,
[Oppervlakte Badkamer (WBS)] [decimal] (12, 2) NULL,
[Oppervlakte Overig (WBS)] [decimal] (12, 2) NULL,
[Oppervlakte VVO] [decimal] (12, 2) NULL,
[Oppervlakte BVO] [decimal] (12, 2) NULL,
[Leegwaarde] [decimal] (12, 2) NULL,
[Beleidswaarde] [decimal] (12, 2) NULL,
[Markthuur TMS] [decimal] (12, 2) NULL,
[Netto marktwaarde] [decimal] (12, 2) NULL,
[Volgnr_] [int] NULL,
[WOZ-peildatum] [date] NULL,
[WOZ-objectnr] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[WOZ-taxatiewaarde] [decimal] (12, 2) NULL,
[Huurklasse_id] [int] NULL,
[Huurklasse_id obv kaal] [int] NULL,
[Huurklasse_id obv streef] [int] NULL,
[Huurklasse_id obv mutatie] [int] NULL,
[Huurklasse_id obv subsidiabel] [int] NULL
) ON [PRIMARY]
GO
