CREATE TABLE [Eenheden].[Woningwaardering]
(
[Woningwaardering_id] [int] NOT NULL IDENTITY(1, 1),
[Bedrijf_id] [int] NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Woningwaardering] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Ingangsdatum] [date] NULL,
[Volgnummer] [int] NULL,
[Einddatum] [date] NULL,
[Totaal punten] [decimal] (12, 2) NULL,
[Totaal punten afgerond] [int] NULL,
[Automatisch berekenen totaal] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Gewijzigd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Datum laatste wijziging] [date] NULL,
[Rijksmonument] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte totaal] [decimal] (12, 2) NULL,
[Oppervlakte vertrekken en overige ruimtes] [decimal] (12, 2) NULL,
[Punten voor vertrekken] [decimal] (12, 2) NULL,
[Oppervlakte berekend (onz)] [decimal] (12, 2) NULL,
[Punten oppervlakte (onz)] [decimal] (12, 2) NULL,
[Punten voor ruimtes] [decimal] (12, 2) NULL,
[Punten gemeenschappelijke ruimtes] [decimal] (12, 2) NULL,
[Punten gemeenschappelijke vertrekken] [decimal] (12, 2) NULL,
[Investering voorzieningen] [decimal] (12, 2) NULL,
[Punten woonvoorzieningen] [decimal] (12, 2) NULL,
[Punten meergezinshuis] [numeric] (12, 2) NULL,
[Duplexwoning] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Eengezinswoning] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Lift (wwd)] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toeslag liften] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Onvrije woning] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Serviceflatwoning] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Verdieping] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[(Eigen) Extra vertrek] [decimal] (12, 2) NULL,
[(Eigen) Keuken] [decimal] (12, 2) NULL,
[(Eigen) Slaapkamer 1] [decimal] (12, 2) NULL,
[(Eigen) Slaapkamer 2] [decimal] (12, 2) NULL,
[(Eigen) Woonkamer] [decimal] (12, 2) NULL,
[Bad + Doucheruimte] [decimal] (12, 2) NULL,
[Badkamer] [decimal] (12, 2) NULL,
[Doucheruimte] [decimal] (12, 2) NULL,
[Extra vertrek(ken)] [decimal] (12, 2) NULL,
[Keuken] [decimal] (12, 2) NULL,
[Serre] [decimal] (12, 2) NULL,
[Slaapkamer 1] [decimal] (12, 2) NULL,
[Slaapkamer 2] [decimal] (12, 2) NULL,
[Slaapkamer 3] [decimal] (12, 2) NULL,
[Slaapkamer 4] [decimal] (12, 2) NULL,
[Slaapkamer 5] [decimal] (12, 2) NULL,
[Slaapkamer 6] [decimal] (12, 2) NULL,
[Woonkamer] [decimal] (12, 2) NULL,
[Woonkamer 2] [decimal] (12, 2) NULL,
[Woonkamer en keuken] [decimal] (12, 2) NULL,
[Zoldervertrek] [decimal] (12, 2) NULL,
[Berging] [decimal] (12, 2) NULL,
[Bijkeuken/Wasruimte] [decimal] (12, 2) NULL,
[Extra berging/-Schuur] [decimal] (12, 2) NULL,
[Garage] [decimal] (12, 2) NULL,
[Gemeensch. fietsenberging] [decimal] (12, 2) NULL,
[Kelder] [decimal] (12, 2) NULL,
[Zolderruimte] [decimal] (12, 2) NULL,
[Aanrechtlengte] [decimal] (12, 2) NULL,
[Categorie aanrechtlengte] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Toilet in badkamer] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Trap naar zolder] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Aantal verwarmde vertrekken] [int] NULL,
[Aantal andere verwarmde ruimtes] [int] NULL,
[Aantal vertrekken met thermische ventielen] [int] NULL,
[Energie adviseur] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Afmelddatum] [date] NULL,
[Energie index] [decimal] (12, 2) NULL,
[Punten energie] [decimal] (12, 2) NULL,
[Energiewaardering] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[EPA-label] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[EPA NTA8800] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Stadsverwarming] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Vergoeding stadsverwarming] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Punten oppervlakte verwarmd] [decimal] (12, 2) NULL,
[Thermostatische regelknoppen] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Punten thermostatische regelknoppen] [int] NULL,
[Gasaansluiting] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Punten gasaansluiting] [int] NULL,
[Punten buitenruimtes] [int] NULL,
[Kwaliteitspunten buiten] [int] NULL,
[Categorie buitenruimte] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Achtertuin] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte achtertuin] [decimal] (12, 2) NULL,
[Voortuin] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte voortuin] [decimal] (12, 2) NULL,
[Zijtuin] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte zijtuin] [decimal] (12, 2) NULL,
[Balkon/terras] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Oppervlakte balkon/terras] [decimal] (12, 2) NULL,
[Carport] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Eigen parkeervoorziening aanwezig] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Met berging] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Met fietsenstalling] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Fietsenberging] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Punten fietsenberging] [int] NULL,
[Type keuken (onz)] [nvarchar] (70) COLLATE Latin1_General_CI_AS NULL,
[Automatisch berekenen keuken] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Totaal punten keuken] [decimal] (12, 2) NULL,
[Kwaliteitspunten keuken] [decimal] (12, 2) NULL,
[Punten algehele luxe keuken] [decimal] (12, 2) NULL,
[Inbouw afzuigkap] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouw koel/vries-combinatie] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouwkoelkast] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouwkookplaat] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouwoven] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouw vaatwasmachine] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouw vrieskist] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Dubbele spoelbak] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inbouw keramische kookplaat] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Extra wandbetegeling keuken] [decimal] (12, 2) NULL,
[Luxe mengkraan keuken] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Thermostatische mengkraan keuken] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Vloertegels] [decimal] (12, 2) NULL,
[Extra kast] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Automatisch berekenen sanitair] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Punten sanitair] [decimal] (12, 2) NULL,
[Kwaliteitspunten sanitair] [decimal] (12, 2) NULL,
[Algehele luxe badgelegenheid] [decimal] (12, 2) NULL,
[Bad + Douche] [int] NULL,
[Bad(en)] [int] NULL,
[Douche(s)] [int] NULL,
[Wastafel(s)] [int] NULL,
[Toilet(ten)] [int] NULL,
[Kastje ingebouwd wastafel] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Extra wandbetegeling bad] [decimal] (12, 2) NULL,
[Luxe mengkraan bad] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Scheerwandcontactdoos] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Thermostatische mengkraan bad] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Toiletkastje ingebouwde verlichting] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Ingebouwde badverwarming] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Schuif-_Vouwwand aluminium] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Douche/bad (onz)] [nvarchar] (40) COLLATE Latin1_General_CI_AS NULL,
[Punten douche/bad (onz)] [int] NULL,
[Wastafel (onz)] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Punten wastafel (onz)] [int] NULL,
[Toilet (onz)] [nvarchar] (40) COLLATE Latin1_General_CI_AS NULL,
[Punten toilet (onz)] [int] NULL,
[Punten schaarstegebied] [decimal] (12, 2) NULL,
[Punten WOZ] [decimal] (12, 2) NULL,
[WOZ waarde (wwd)] [decimal] (12, 2) NULL,
[Bouwjaar] [int] NULL,
[Reden afwijkende WOZ id] [int] NULL,
[(Aftrek) Vloeropp <10 m²] [int] NULL,
[(Aftrek) Overlast] [int] NULL,
[(Aftrek) Toilet indirect bereikbaar] [int] NULL,
[(Aftrek) Verdieping > 4 zonder lift] [int] NULL,
[(Aftrek) Ramen <0,75 m²] [int] NULL,
[(Aftrek) Raam hoger 1,6 m] [int] NULL,
[(Aftrek) Gevel <5 m] [int] NULL,
[(Aftrek) Niet koken] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Woningwaardering_01] ON [Eenheden].[Woningwaardering] ([Bedrijf_id], [Eenheidnr], [Ingangsdatum]) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [Woningwaardering_PK] ON [Eenheden].[Woningwaardering] ([Woningwaardering_id]) ON [PRIMARY]
GO
