CREATE TABLE [Empire].[2C Secured Table]
(
[timestamp] [timestamp] NOT NULL,
[Type] [int] NOT NULL,
[No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Description] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[Table ID] [int] NOT NULL,
[Table Name] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Table Caption] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Starting Date] [datetime] NOT NULL,
[Ending Date] [datetime] NOT NULL,
[Data Owner] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Default Editable] [tinyint] NOT NULL,
[Scope] [int] NOT NULL,
[App ID] [uniqueidentifier] NOT NULL,
[Module] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Table Type] [int] NOT NULL,
[No_ Series] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[FS_Insert Check] [tinyint] NOT NULL,
[FS_Modify Check] [tinyint] NOT NULL,
[FS_Delete Check] [tinyint] NOT NULL,
[DS_Insert Check] [tinyint] NOT NULL,
[DS_Modify Check Current Value] [tinyint] NOT NULL,
[DS_Modify Check New Value] [tinyint] NOT NULL,
[DS_Delete Check] [tinyint] NOT NULL,
[Filter Field No_] [int] NOT NULL,
[Filter Field Name] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Filter Field Caption] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Filter Value] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Internal Filter Value] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
