CREATE TABLE [Empire].[Staedion$User Setup]
(
[timestamp] [timestamp] NOT NULL,
[User ID] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Allow Posting From] [datetime] NOT NULL,
[Allow Posting To] [datetime] NOT NULL,
[Register Time] [tinyint] NOT NULL,
[Salespers__Purch_ Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Approver ID] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Sales Amount Approval Limit] [int] NOT NULL,
[Purchase Amount Approval Limit] [int] NOT NULL,
[Unlimited Sales Approval] [tinyint] NOT NULL,
[Unlimited Purchase Approval] [tinyint] NOT NULL,
[Substitute] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[E-Mail] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[Request Amount Approval Limit] [int] NOT NULL,
[Unlimited Request Approval] [tinyint] NOT NULL,
[Time Sheet Admin_] [tinyint] NOT NULL,
[Allow FA Posting From] [datetime] NOT NULL,
[Allow FA Posting To] [datetime] NOT NULL,
[Sales Resp_ Ctr_ Filter] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Purchase Resp_ Ctr_ Filter] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Service Resp_ Ctr_ Filter] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Responsibility Center] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Global Dimension 1 Filter] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Deurwaarder] [tinyint] NOT NULL,
[Blokk_ Dimwijz_ Grootboekrek_] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Grootboekrek_filter Lezen] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Grootboekrek_filter Boeken] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Grootboekrek_filter Invoegen] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Appl_beheerder huurtoeslag] [tinyint] NOT NULL,
[Boekingsdatum mutabel] [int] NOT NULL,
[Prolongatie] [tinyint] NOT NULL,
[Elementposten verwijderen] [tinyint] NOT NULL,
[Remove Cost Code Entries] [tinyint] NOT NULL,
[Approver] [tinyint] NOT NULL,
[Name] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[CorrKostSrtRepVrzkMetPosten] [tinyint] NOT NULL,
[Verhuurmutaties accorderen] [tinyint] NOT NULL,
[Registratiedatum wijzigen] [tinyint] NOT NULL,
[Verhuurmutaties fiatteren] [tinyint] NOT NULL,
[Projecttypefilter] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Permissie budgetw_kladblok] [tinyint] NOT NULL,
[Permissie heropenen project] [tinyint] NOT NULL,
[Permissie ingave prognose] [tinyint] NOT NULL,
[Permissie blokkeren] [tinyint] NOT NULL,
[Permissie wijzigen status_fase] [tinyint] NOT NULL,
[Permissie accorderen uren] [tinyint] NOT NULL,
[Permissie boeken uren] [tinyint] NOT NULL,
[Permissie budgetwijziging proj] [tinyint] NOT NULL,
[Permissie handm_invoer kladbl_] [tinyint] NOT NULL,
[Permissie handm_invoer project] [tinyint] NOT NULL,
[Reopen Awarded Order] [tinyint] NOT NULL,
[Gen_ kenmerkenmodule] [tinyint] NOT NULL,
[Blokkeren financieringen] [tinyint] NOT NULL,
[Accorderen financieringsmodel] [tinyint] NOT NULL,
[Accorderen financieringsvorm] [tinyint] NOT NULL,
[Accorderen kasstroom] [tinyint] NOT NULL,
[Accorderen rentepercentage] [tinyint] NOT NULL,
[Salesperson Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Postcodecontrole negeren] [tinyint] NOT NULL,
[Change Complaint Status] [tinyint] NOT NULL,
[Replacement Purch Inv_Credit] [tinyint] NOT NULL,
[Publicatiecontrole wijzigen] [tinyint] NOT NULL,
[Gas_elektra gecontroleerd] [tinyint] NOT NULL,
[Permissie heropenen reparatiev] [tinyint] NOT NULL,
[Projectfilter] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[S&V-afrekeningen fiatteren] [tinyint] NOT NULL,
[S&V-afrekeningstatus wijzigen] [tinyint] NOT NULL,
[Bemiddelingsstatus wijzigen] [tinyint] NOT NULL,
[Mut_proces ToonAfgehandeld] [tinyint] NOT NULL,
[Verhuuraanbieding wijzigen] [tinyint] NOT NULL,
[Bouwnummers vrijgeven] [tinyint] NOT NULL,
[Permissie heropenen projectfas] [tinyint] NOT NULL,
[Fixture Type Filter] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Service Call Type Filter] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Interaction Templ_ Code Filter] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Surcharge Allowed] [tinyint] NOT NULL,
[Dech_ Home Address Allowed] [tinyint] NOT NULL,
[Dech_ OA Member Allowed] [tinyint] NOT NULL,
[Manually Close Purchase Order] [tinyint] NOT NULL,
[Wijzigen fin_boekingsgroep] [tinyint] NOT NULL,
[Wijzigen geldgever-ID] [tinyint] NOT NULL,
[Wijzigen grootboekintegratie] [tinyint] NOT NULL,
[Ignore Maintenance Errors] [tinyint] NOT NULL,
[Responsibility Center Check] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Remove permissions Em-Planner] [tinyint] NOT NULL,
[Approval Level] [int] NOT NULL,
[Deduplicate Contacts] [tinyint] NOT NULL,
[Enable Lync Integration] [tinyint] NOT NULL,
[Create New Rental Just_] [tinyint] NOT NULL,
[Activate Cluster Distr Key] [tinyint] NOT NULL,
[Activate Proj BudgLn Distr Key] [tinyint] NOT NULL,
[Approval Administrator] [tinyint] NOT NULL,
[Overrule TenantAgreesToCosts] [tinyint] NOT NULL,
[Change Lib_ Contract Ind_] [tinyint] NOT NULL,
[Activate Change OGE Adm_ Owner] [tinyint] NOT NULL,
[Bailiff No_] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Send AE Payment Request] [tinyint] NOT NULL
) ON [PRIMARY]
GO
