CREATE TABLE [Excel].[tmp_bik_2020]
(
[Cluster] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Clusternaam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Cluster2] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Aantal woningen] [float] NULL,
[Thuisteam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Bewonersconsulent] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Buurt] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Rapport cijfer-op complexniveau] [float] NULL,
[Thuisgevoel] [float] NULL,
[Tevredenheid woning] [float] NULL,
[Tevredenheid algemene ruimte] [float] NULL,
[Tevredenheid Buurt] [float] NULL,
[KCM rapportcijfer ] [float] NULL,
[Aantal meldingen overlast] [float] NULL,
[% overlast] [float] NULL,
[Rapport cijfer overlast] [float] NULL,
[Aantal meldingen woonfraude] [float] NULL,
[% woonfraude] [float] NULL,
[Rapportcijfer woonfraude] [float] NULL,
[Eindcijfer overlast & wooonfraude] [float] NULL,
[Leefbaarheid:                                  A# Overlast] [float] NULL,
[Leefbaarheid:                                  B# Vervuiling] [float] NULL,
[Gemiddelde Leefbaarheid: Overlast/ Vervuiling] [float] NULL,
[Criminaliteit & Woonfraude] [float] NULL,
[Participatie] [float] NULL,
[Leefkwaliteit] [float] NULL,
[Huidige beheerintensiteit] [float] NULL,
[Teamscore] [float] NULL,
[Complex score] [float] NULL,
[Jaar] [float] NULL
) ON [PRIMARY]
GO
