CREATE TABLE [Financieel].[Facturen]
(
[Bedrijf_id] [int] NULL,
[Factuurnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Documentsoort_id] [int] NULL,
[Brontabel] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Transactie soort] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Leveranciernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Naam leverancier] [nvarchar] (105) COLLATE Latin1_General_CI_AS NULL,
[Factuurnr leverancier] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Factuurnr creditfactuur] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Documentdatum] [date] NULL,
[Factuurstatus] [int] NULL,
[Geboekt] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Boekdatum] [date] NULL,
[Vervaldatum] [date] NULL,
[Betalingsconditie] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Afwachtcode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Norm vervaldagen] [int] NULL,
[Open] [smallint] NULL,
[Afgesloten op] [date] NULL,
[Btw productboekingsgroepen] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Zowel verlegde als gewone btw] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inkoper] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Inkoper naam] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Toegewezen gebruiker] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Afdeling] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Bedrijfsonderdeel] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Betaling in Telebank] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Bedrag in Telebank] [decimal] (12, 2) NULL,
[Bedrag naar G-rekening] [decimal] (12, 2) NULL,
[Bedrag naar N-rekening] [decimal] (12, 2) NULL,
[Percentage naar G-rekening] [decimal] (6, 2) NULL,
[G-rekeningnummer] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[N-rekeningnummer] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Betaaldatum] [date] NULL,
[Factuurbedrag] [decimal] (12, 2) NULL,
[Factuurbedrag excl btw] [decimal] (12, 2) NULL,
[Btw] [decimal] (12, 2) NULL,
[Factuurbedrag uit lev. posten] [decimal] (12, 2) NULL,
[GB tussenrekening handelsdebiteuren] [decimal] (12, 2) NULL,
[GB btw rekeningen] [decimal] (12, 2) NULL,
[Hyperlink Klantvenster] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Hyperlink Empire] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Goedkeuringssoort] [nvarchar] (40) COLLATE Latin1_General_CI_AS NULL,
[Projectsoort] [nvarchar] (40) COLLATE Latin1_General_CI_AS NULL,
[Eerste goedkeuring] [datetime] NULL,
[Laatste goedkeuring] [datetime] NULL,
[Goedkeurders] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Aantal goedkeuringsposten] [int] NULL,
[Geboekte goedkeurders] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Aantal geboekte goedkeuringsposten] [int] NULL,
[Doorlooptijd] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Fiatteurs] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Eerste goedkeurder] [nvarchar] (40) COLLATE Latin1_General_CI_AS NULL,
[Laatste goedkeurder] [nvarchar] (40) COLLATE Latin1_General_CI_AS NULL,
[Opmerking] [nvarchar] (75) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
