CREATE TABLE [Financieel].[Factuurregels]
(
[Bedrijf_id] [int] NULL,
[Factuurnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Regelnr] [int] NULL,
[Omschrijving] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Omschrijving 2] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Orderregel] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Regelsoort_id] [int] NULL,
[Verwachte factuurdatum] [date] NULL,
[Betaling in telebank] [char] (3) COLLATE Latin1_General_CI_AS NULL,
[Dimension Set ID] [int] NULL,
[Kostenplaats] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Empire Werksoort] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Posting Status] [int] NULL,
[Empire Budgetregel] [int] NULL,
[Regelbedrag] [decimal] (12, 2) NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Aantal] [decimal] (12, 2) NULL,
[Btw perc] [decimal] (6, 2) NULL,
[Kortingperc] [decimal] (6, 2) NULL,
[Korting bedrag] [decimal] (12, 2) NULL,
[Bedrag] [decimal] (12, 2) NULL,
[Maintenance Order No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[taaknpo] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Prijs per eenheid] [decimal] (12, 2) NULL,
[Kosten] [decimal] (12, 2) NULL,
[Bedrag incl btw] [decimal] (12, 2) NULL,
[Btw] [decimal] (12, 2) NULL,
[Btw productboekingsgroep] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Opslag] [decimal] (12, 2) NULL,
[Projectnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[BTW berekeningssoort] [int] NULL,
[Integratieheffing] [int] NULL,
[Clusternr] [varchar] (20) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
