CREATE TABLE [Huuraanpassing].[Staedion$Prop_ Valuation (Shared Acc_)]
(
[timestamp] [timestamp] NOT NULL,
[Eenheidnr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Ingangsdatum] [datetime] NOT NULL,
[Volgnummer] [int] NOT NULL,
[Totaal punten afgerond] [int] NOT NULL,
[(Eigen) Verwarmde vertrekken] [numeric] (38, 20) NOT NULL,
[(Eigen) Thermost_regelknoppen] [tinyint] NOT NULL,
[(Eigen) Gasaansluiting] [tinyint] NOT NULL,
[Douche_bad] [int] NOT NULL,
[Wastafel] [int] NOT NULL,
[Toilet] [int] NOT NULL,
[Keuken] [int] NOT NULL,
[Buitenruimte] [int] NOT NULL,
[Fietsenberging] [int] NOT NULL,
[(Gem_) Verblijfsruimte(s)] [numeric] (38, 20) NOT NULL,
[(Gem_) Per##kamers] [int] NOT NULL,
[(Aftrek) Verdieping+4] [tinyint] NOT NULL,
[(Aftrek) Vloeropp <10] [tinyint] NOT NULL,
[(Aftrek) Indirect bereikbaar] [tinyint] NOT NULL,
[(Aftrek) Ramen <0,75] [tinyint] NOT NULL,
[(Aftrek) Raam hoger 1,6] [tinyint] NOT NULL,
[(Aftrek) Gevel <5] [tinyint] NOT NULL,
[(Aftrek) Overlast] [tinyint] NOT NULL,
[(Aftrek) Niet koken] [tinyint] NOT NULL,
[Automatisch berekenen totaal] [tinyint] NOT NULL,
[Jaar] [int] NOT NULL,
[Einddatum] [datetime] NOT NULL,
[Totaal punten] [numeric] (38, 20) NOT NULL,
[Totaal vertrekken] [numeric] (38, 20) NOT NULL,
[Totaal punten zonder aftrek] [numeric] (38, 20) NOT NULL,
[Last date modified] [datetime] NOT NULL,
[Changed By] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Total Surface] [numeric] (38, 20) NOT NULL,
[National Monument] [tinyint] NOT NULL,
[Open] [tinyint] NOT NULL,
[Maximum Rent Price] [numeric] (38, 20) NOT NULL,
[Protected City or Village View] [tinyint] NOT NULL,
[Maximum Rent Price Raise Perc_] [numeric] (38, 20) NOT NULL,
[Maximum Rent Price excl_ Raise] [numeric] (38, 20) NOT NULL,
[ConstructionYear] [int] NOT NULL
) ON [PRIMARY]
GO
