CREATE TABLE [Huuraanpassing].[Staedion$CR-gegevens]
(
[timestamp] [timestamp] NOT NULL,
[Coderegeling] [int] NOT NULL,
[Ingangsdatum] [datetime] NOT NULL,
[Einddatum] [datetime] NOT NULL,
[Ondergrens huur] [numeric] (38, 20) NOT NULL,
[Bovengrens < 23 jr_ zndr kndr_] [numeric] (38, 20) NOT NULL,
[Bovengrens huur overig] [numeric] (38, 20) NOT NULL,
[1e overgangsregelings_] [numeric] (38, 20) NOT NULL,
[2e overgangsregelings_] [numeric] (38, 20) NOT NULL,
[Peildatum leeftijd huishouden] [datetime] NOT NULL,
[Inkomensgrens 1pers_h_h_] [numeric] (38, 20) NOT NULL,
[Inkomensgrens meerpers_h_h_] [numeric] (38, 20) NOT NULL,
[Inkomensgrens 1pers_o_h_h_] [numeric] (38, 20) NOT NULL,
[Inkomensgrens meerpers_o_h_h_] [numeric] (38, 20) NOT NULL,
[Peildatum leeftijd vermogen] [datetime] NOT NULL,
[Vermogensgrens 1pers_<64] [numeric] (38, 20) NOT NULL,
[Vermogensgrens meerpers_<64] [numeric] (38, 20) NOT NULL,
[Vermogensgrens 1pers_64+] [numeric] (38, 20) NOT NULL,
[Vermogensgrens meerpers_64+] [numeric] (38, 20) NOT NULL,
[Standaardaftrek_ loon] [numeric] (38, 20) NOT NULL,
[Ondergrens loon] [numeric] (38, 20) NOT NULL,
[Bovengrens loon] [numeric] (38, 20) NOT NULL,
[Standaardaftrek uitkering] [numeric] (38, 20) NOT NULL,
[Standaardaftr__ loon bij comb_] [numeric] (38, 20) NOT NULL,
[Ondergrens combinatie] [numeric] (38, 20) NOT NULL,
[Bovengrens combinatie] [numeric] (38, 20) NOT NULL,
[Aftoppingsgrens1] [numeric] (38, 20) NOT NULL,
[Aftoppingsgrens2] [numeric] (38, 20) NOT NULL,
[Kortingsgrens] [numeric] (38, 20) NOT NULL,
[Toeslag1] [numeric] (38, 20) NOT NULL,
[Toeslag2] [numeric] (38, 20) NOT NULL,
[Toeslag3] [numeric] (38, 20) NOT NULL,
[Toeslag4] [numeric] (38, 20) NOT NULL,
[Ondergrens subsidie] [numeric] (38, 20) NOT NULL,
[Element(en) 2b] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Bedrag 2b] [numeric] (38, 20) NOT NULL,
[Subs_element(en) 2f] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Max_bedrag 2f] [numeric] (38, 20) NOT NULL,
[Subs_element(en) 2g] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Max_bedrag 2g] [numeric] (38, 20) NOT NULL,
[Subs_element(en) 2h] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Max_bedrag 2h] [numeric] (38, 20) NOT NULL,
[Subs_element(en) 2i] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Max_bedrag 2i] [numeric] (38, 20) NOT NULL,
[Element(en) 2c] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Kinderaftrek inkomen] [numeric] (38, 20) NOT NULL,
[Kinderaftrek vermogen] [numeric] (38, 20) NOT NULL,
[Basic Amount Elements] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
