CREATE TABLE [Huuraanpassing].[Customer]
(
[timestamp] [timestamp] NOT NULL,
[No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Name] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Search Name] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Name 2] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Address] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Address 2] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[City] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Contact] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Phone No_] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Telex No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Our Account No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Territory Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Global Dimension 1 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Global Dimension 2 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Chain Name] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Budgeted Amount] [numeric] (38, 20) NOT NULL,
[Credit Limit (LCY)] [numeric] (38, 20) NOT NULL,
[Customer Posting Group] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Currency Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Customer Price Group] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Language Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Statistics Group] [int] NOT NULL,
[Payment Terms Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Fin_ Charge Terms Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Salesperson Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Shipment Method Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Shipping Agent Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Place of Export] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Invoice Disc_ Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Customer Disc_ Group] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Country_Region Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Collection Method] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Amount] [numeric] (38, 20) NOT NULL,
[Blocked] [int] NOT NULL,
[Invoice Copies] [int] NOT NULL,
[Last Statement No_] [int] NOT NULL,
[Print Statements] [tinyint] NOT NULL,
[Bill-to Customer No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Priority] [int] NOT NULL,
[Payment Method Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Last Date Modified] [datetime] NOT NULL,
[Application Method] [int] NOT NULL,
[Prices Including VAT] [tinyint] NOT NULL,
[Location Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Fax No_] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Telex Answer Back] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[VAT Registration No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Combine Shipments] [tinyint] NOT NULL,
[Gen_ Bus_ Posting Group] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Picture] [image] NULL,
[Post Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[County] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[E-Mail] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Home Page] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Reminder Terms Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[No_ Series] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Tax Area Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Tax Liable] [tinyint] NOT NULL,
[VAT Bus_ Posting Group] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Reserve] [int] NOT NULL,
[Block Payment Tolerance] [tinyint] NOT NULL,
[IC Partner Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Prepayment _] [numeric] (38, 20) NOT NULL,
[Partner Type] [int] NOT NULL,
[Preferred Bank Account Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Cash Flow Payment Terms Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Primary Contact No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Responsibility Center] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Shipping Advice] [int] NOT NULL,
[Shipping Time] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL,
[Shipping Agent Service Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Service Zone Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Allow Line Disc_] [tinyint] NOT NULL,
[Base Calendar Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Copy Sell-to Addr_ to Qte From] [int] NOT NULL,
[Oud nummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Factuurtype] [int] NOT NULL,
[Telefoon overdag] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Payment Scheme Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Naam 3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Naam 4] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Telefoon 3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Telefoon 4] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Telefoon 5] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Mobiel] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Mobiel 2] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Mobiel 3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Mobiel 4] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Mobiel 5] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[E-mail 2] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[E-mail 3] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[E-mail 4] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[E-mail 5] [nvarchar] (80) COLLATE Latin1_General_CI_AS NOT NULL,
[Transactiewijze excasso] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Telefoon 2] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Woningzoekende] [tinyint] NOT NULL,
[Geslacht] [int] NOT NULL,
[Burgerlijke staat] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[SoFi-nummer] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Woonbonnr_] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[IHS geblokkeerd] [tinyint] NOT NULL,
[Datum blokkade] [datetime] NOT NULL,
[Buurt] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Handelsregisternr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Factuurtype diensten] [int] NOT NULL,
[Transactiewijze diensten] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[To be deleted ID - 61118] [datetime] NOT NULL,
[VAT Obligation] [tinyint] NOT NULL,
[Huurdersverklaring] [tinyint] NOT NULL,
[Sleperniveau] [int] NOT NULL,
[Contact No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[To be deleted ID - 61203] [datetime] NOT NULL,
[Transaction Mode Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Aanmaningsniveau] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Customer Type] [int] NOT NULL,
[Sorting ID] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Combine Invoices by] [int] NOT NULL,
[Document Sending Profile] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[GLN] [nvarchar] (13) COLLATE Latin1_General_CI_AS NOT NULL,
[Image] [uniqueidentifier] NOT NULL,
[Automatic Posting] [tinyint] NOT NULL,
[Automatic Accept Requests] [tinyint] NOT NULL,
[Take Away Material Charge _ RC] [numeric] (38, 20) NOT NULL,
[Vendor Charge _ RC] [numeric] (38, 20) NOT NULL,
[Vendor Discount _ RC] [numeric] (38, 20) NOT NULL,
[CustomerPortalAccountStatus] [int] NOT NULL
) ON [PRIMARY]
GO
