CREATE TABLE [Huuraanpassing].[staedion$Contract]
(
[timestamp] [timestamp] NOT NULL,
[Soort] [int] NOT NULL,
[Eenheidnr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Volgnr_] [int] NOT NULL,
[Customer No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Naam] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Status] [int] NOT NULL,
[Ingangsdatum] [datetime] NOT NULL,
[Einddatum] [datetime] NOT NULL,
[Beëindigd] [tinyint] NOT NULL,
[Prolongatietermijn] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL,
[Geprolongeerd tot] [datetime] NOT NULL,
[Prolongatiedatum] [datetime] NOT NULL,
[Indexeringsdatum] [datetime] NOT NULL,
[Weigeringsbedrag] [numeric] (38, 20) NOT NULL,
[Huisnr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Toevoegsel] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Indexcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Indexeringsmethode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Markthuurwaarde (LV)] [numeric] (38, 20) NOT NULL,
[Bedrijfsboekingsgrp_ leegstand] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Boekingsgroep] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[BTW-bedrijfsb_grp_ leegstand] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Ingangsdatum weigering] [datetime] NOT NULL,
[Indexeringsbatchnaam] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Indexering verwerkt] [tinyint] NOT NULL,
[Bezwaar huurverhoging] [tinyint] NOT NULL,
[Coderegeling] [int] NOT NULL,
[Postcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Vervallen indexeringsdatum] [datetime] NOT NULL,
[Eindafrekening] [datetime] NOT NULL,
[Valutacode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Factureren in] [int] NOT NULL,
[Huurprijsliberalisatie] [tinyint] NOT NULL,
[Motivering verplicht] [tinyint] NOT NULL,
[Gemaximaliseerd] [tinyint] NOT NULL,
[Huurvastperiode] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL,
[Einddatum huurvastperiode] [datetime] NOT NULL,
[Bezwaar toegewezen] [tinyint] NOT NULL,
[Moedercontract] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Soort uitgifte] [int] NOT NULL,
[Datum overdracht] [datetime] NOT NULL,
[Duur moedercontract] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL,
[WM afkoop einddatum] [datetime] NOT NULL,
[Grondeigenaar] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Datum heroverweging] [datetime] NOT NULL,
[Soort heroverweging] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Huidige canon] [numeric] (38, 20) NOT NULL,
[Opslag _ canon verkoop] [numeric] (38, 20) NOT NULL,
[Afkoopsom] [numeric] (38, 20) NOT NULL,
[Afgekocht] [tinyint] NOT NULL,
[Afgekocht per] [datetime] NOT NULL,
[Afkooptermijn] [numeric] (38, 20) NOT NULL,
[Afgekocht tot] [datetime] NOT NULL,
[Afschrijving vergoeding] [int] NOT NULL,
[Percentage afschrijving] [numeric] (38, 20) NOT NULL,
[Bedrag afschrijving vergoeding] [numeric] (38, 20) NOT NULL,
[Cluster No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Nr_reeks] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Moedercontractvolgnr_] [int] NOT NULL,
[Opmerkingen] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Grondslag indexering] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Aantal m2] [numeric] (38, 20) NOT NULL,
[Grondwaarde (LV)] [numeric] (38, 20) NOT NULL,
[Betalingsbereid] [tinyint] NOT NULL,
[Afkooptermijn (formule)] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL,
[Aangemaakt vanuit S&V-module] [tinyint] NOT NULL,
[Aanbiedingsvorm] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Aanbiedingssoort] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Eindbedrag huurzeker] [numeric] (38, 20) NOT NULL,
[Huurzekerpercentage] [numeric] (38, 20) NOT NULL,
[Rent increase applied] [tinyint] NOT NULL,
[Verkoop] [tinyint] NOT NULL,
[Huurtoeslag] [tinyint] NOT NULL,
[Objection Status] [int] NOT NULL,
[Date Withdraw,Granted,Rejected] [datetime] NOT NULL,
[Reason Code Wdrwn,Grntd,Rejtd] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Livability Dossier No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Aangemaakt op] [datetime] NOT NULL,
[Responsibility Center] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Verhuuraanbiedingvolgnr_] [int] NOT NULL,
[Sorting ID] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Income Class Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Dummy Contract] [tinyint] NOT NULL,
[Exploitation State Type] [int] NOT NULL,
[Exploitation End Reason Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Sales Proposal No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_Staedion$Contract_Eenheidnr_Volgnr_] ON [Huuraanpassing].[staedion$Contract] ([Eenheidnr_], [Volgnr_]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_Staedion$Contract_Status_Eenheidnr_Customer_No_] ON [Huuraanpassing].[staedion$Contract] ([Status], [Eenheidnr_], [Customer No_]) ON [PRIMARY]
GO
