CREATE TABLE [Huuraanpassing].[Staedion$Property Valuation]
(
[timestamp] [timestamp] NOT NULL,
[Eenheidnr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Ingangsdatum] [datetime] NOT NULL,
[Volgnummer] [int] NOT NULL,
[Totaal punten afgerond] [int] NOT NULL,
[Stadsverwarming] [tinyint] NOT NULL,
[Aantal verwarmde vertrekken] [int] NOT NULL,
[Aantal andere verw_ ruimtes] [int] NOT NULL,
[Aantal vertrekken therm_vent_] [int] NOT NULL,
[Individuele C_V_-ketel] [tinyint] NOT NULL,
[Individuele H_R_-ketel] [tinyint] NOT NULL,
[Collectieve H_R_-ketel] [tinyint] NOT NULL,
[Doorstroommeter] [tinyint] NOT NULL,
[Individuele C_V_-combi] [tinyint] NOT NULL,
[Collectieve warmwater-voorz_] [tinyint] NOT NULL,
[Video Phone] [tinyint] NOT NULL,
[Spouwisolatie Voor_Achtergevel] [tinyint] NOT NULL,
[Vloerisolatie] [tinyint] NOT NULL,
[Dakisolatie] [tinyint] NOT NULL,
[Gevelisolatie] [tinyint] NOT NULL,
[Meergezinshuis] [numeric] (38, 20) NOT NULL,
[Oorspronkelijke investering] [numeric] (38, 20) NOT NULL,
[Kwaliteitspunten keuken] [numeric] (38, 20) NOT NULL,
[Bad(en)] [int] NOT NULL,
[Douche(s)] [int] NOT NULL,
[Bad + Douche] [int] NOT NULL,
[Toilet(ten)] [int] NOT NULL,
[Wastafel(s)] [int] NOT NULL,
[Kwaliteitspunten sanitair] [numeric] (38, 20) NOT NULL,
[Bouwjaar] [int] NOT NULL,
[Bouwtechnische staat] [numeric] (38, 20) NOT NULL,
[Reductie investering] [numeric] (38, 20) NOT NULL,
[Voortuin] [numeric] (38, 20) NOT NULL,
[Zijtuin] [numeric] (38, 20) NOT NULL,
[Achtertuin] [numeric] (38, 20) NOT NULL,
[Balkon_Terras] [numeric] (38, 20) NOT NULL,
[Kwaliteitspunten buiten] [int] NOT NULL,
[Carport] [tinyint] NOT NULL,
[Eengezinswoning] [int] NOT NULL,
[Verdieping] [int] NOT NULL,
[Lift] [tinyint] NOT NULL,
[Duplexwoning] [int] NOT NULL,
[Toeslag liften] [tinyint] NOT NULL,
[Onvrije woning] [tinyint] NOT NULL,
[Kwaliteitspunten woonomgeving] [numeric] (38, 20) NOT NULL,
[Totaal vertrekken] [numeric] (38, 20) NOT NULL,
[Totaal ruimtes] [numeric] (38, 20) NOT NULL,
[Totaal verwarming] [numeric] (38, 20) NOT NULL,
[Totaal isolatie (max_)] [numeric] (38, 20) NOT NULL,
[Totaal keuken] [numeric] (38, 20) NOT NULL,
[Totaal sanitair] [numeric] (38, 20) NOT NULL,
[Totaal veroudering] [numeric] (38, 20) NOT NULL,
[Totaal buitenruimtes] [int] NOT NULL,
[Totaal woonvorm] [int] NOT NULL,
[Totaal woonomgeving] [numeric] (38, 20) NOT NULL,
[Investering voorzieningen] [numeric] (38, 20) NOT NULL,
[Totaal woonvoorzieningen] [numeric] (38, 20) NOT NULL,
[Totaal WOZ] [numeric] (38, 20) NOT NULL,
[Serviceflatwoning] [tinyint] NOT NULL,
[Automatisch berekenen totaal] [tinyint] NOT NULL,
[Totaal hinder] [numeric] (38, 20) NOT NULL,
[Aftrek bouwjaar] [numeric] (38, 20) NOT NULL,
[Totaal punten] [numeric] (38, 20) NOT NULL,
[Inbouwkookplaat] [tinyint] NOT NULL,
[Keramische inbouwkookplaat] [tinyint] NOT NULL,
[Inbouwoven] [tinyint] NOT NULL,
[Inbouwafzuigkap] [tinyint] NOT NULL,
[Inbouwkoelkast] [tinyint] NOT NULL,
[Inbouwvrieskist] [tinyint] NOT NULL,
[Inbouwkoel-_vriescombinatie] [tinyint] NOT NULL,
[Inbouwvaatwasmachine] [tinyint] NOT NULL,
[Extra kast] [tinyint] NOT NULL,
[Luxe mengkraan keuken] [tinyint] NOT NULL,
[Thermost_ mengkraan keuken] [tinyint] NOT NULL,
[Dubbele spoelbak] [tinyint] NOT NULL,
[Extra wandbetegeling keuken] [numeric] (38, 20) NOT NULL,
[Vloertegels] [numeric] (38, 20) NOT NULL,
[Extra wandbetegeling bad] [numeric] (38, 20) NOT NULL,
[Kastje ingebouwd wastafel] [tinyint] NOT NULL,
[Toiletkastje ingebouwde verl_] [tinyint] NOT NULL,
[Scheerwandcontactdoos] [tinyint] NOT NULL,
[Luxe mengkraan bad] [tinyint] NOT NULL,
[Thermostat_ mengkraan bad] [tinyint] NOT NULL,
[Ingebouwde badverwarming] [tinyint] NOT NULL,
[Schuif-_vouwwand aluminium] [tinyint] NOT NULL,
[Algehele luxe keuken] [numeric] (38, 20) NOT NULL,
[Algehele luxe badgelegenheid] [numeric] (38, 20) NOT NULL,
[Jaar] [int] NOT NULL,
[Automatisch berekenen keuken] [tinyint] NOT NULL,
[Automatisch berekenen sanitair] [tinyint] NOT NULL,
[Automatisch berekenen woonomg_] [tinyint] NOT NULL,
[Last date modified] [datetime] NOT NULL,
[Changed By] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Aantal extra kasten] [int] NOT NULL,
[Outdoor Space Category] [int] NOT NULL,
[Total Worktop Points] [int] NOT NULL,
[Frontyard Present] [tinyint] NOT NULL,
[Sideyard Present] [tinyint] NOT NULL,
[Backyard Present] [tinyint] NOT NULL,
[Balcony_Terrace Present] [tinyint] NOT NULL,
[Total Area Rooms MT] [numeric] (38, 20) NOT NULL,
[Factor Heated Rooms] [numeric] (38, 20) NOT NULL,
[Factor Other Heated] [numeric] (38, 20) NOT NULL,
[Heating Subtotal 1] [numeric] (38, 20) NOT NULL,
[Heating Subtotal 2] [numeric] (38, 20) NOT NULL,
[Total Installations] [numeric] (38, 20) NOT NULL,
[Points Outdoor Spaces] [numeric] (38, 20) NOT NULL,
[Addition Serviced Flat] [numeric] (38, 20) NOT NULL,
[Points Investment Facilities] [numeric] (38, 20) NOT NULL,
[Points Original Investment] [numeric] (38, 20) NOT NULL,
[Points Double Glazing] [numeric] (38, 20) NOT NULL,
[Total Isolation] [numeric] (38, 20) NOT NULL,
[Points Addition Elevators] [numeric] (38, 20) NOT NULL,
[Total Quality Kitchen] [numeric] (38, 20) NOT NULL,
[Total Quality Sanitation] [numeric] (38, 20) NOT NULL,
[Improvement Plan] [tinyint] NOT NULL,
[Tot_ Area Room As Space MT] [numeric] (38, 20) NOT NULL,
[Tot_ Area Rooms Not Counted MT] [numeric] (38, 20) NOT NULL,
[Tot_ Counted Spaces Adj_] [numeric] (38, 20) NOT NULL,
[Tot_ Not Counted Spaces Adj_] [numeric] (38, 20) NOT NULL,
[Punten gemeensch_vertrekken] [numeric] (38, 20) NOT NULL,
[Punten gemeensch_ruimtes] [numeric] (38, 20) NOT NULL,
[Einddatum] [datetime] NOT NULL,
[Vergoeding stadsverwarming] [tinyint] NOT NULL,
[Punten spouwisolatie v_a-gevel] [numeric] (38, 20) NOT NULL,
[Spouwisolatie zij(kop)gevel(s)] [tinyint] NOT NULL,
[Punten spouwisolatie z_k-gevel] [numeric] (38, 20) NOT NULL,
[Punten vloerisolatie] [numeric] (38, 20) NOT NULL,
[Punten dakisolatie] [numeric] (38, 20) NOT NULL,
[Punten gevelisolatie] [numeric] (38, 20) NOT NULL,
[Aftopping punten woonomgeving] [tinyint] NOT NULL,
[Aftoppingspercentage] [numeric] (38, 20) NOT NULL,
[Aftoppingspunten woonomgeving] [numeric] (38, 20) NOT NULL,
[Totaal woonomgeving afgetopt] [numeric] (38, 20) NOT NULL,
[Opp_ vertr_+ov_ruimtes] [numeric] (38, 20) NOT NULL,
[Total Surface] [numeric] (38, 20) NOT NULL,
[Energy Validation] [int] NOT NULL,
[Energy Points] [numeric] (38, 20) NOT NULL,
[EPA-label] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Certificate Granted] [datetime] NOT NULL,
[Advisor No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Addition Scarcity Area] [numeric] (38, 20) NOT NULL,
[Deduction Elevator] [tinyint] NOT NULL,
[Points Deduction Elevator] [numeric] (38, 20) NOT NULL,
[National Monument] [tinyint] NOT NULL,
[Open] [tinyint] NOT NULL,
[Points shared Outdoor Space] [numeric] (38, 20) NOT NULL,
[Energy Index] [numeric] (38, 20) NOT NULL,
[WOZ Value] [numeric] (38, 20) NOT NULL,
[Area Rooms & Spaces from 2 m2] [numeric] (38, 20) NOT NULL,
[High Quality Renovation] [tinyint] NOT NULL,
[Points Renovation Investment] [numeric] (38, 20) NOT NULL,
[COROP Area Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Built-in Combi-Oven_Microwave] [tinyint] NOT NULL,
[Whirlpool] [tinyint] NOT NULL,
[Wall Toilet_Floating Toilet] [tinyint] NOT NULL,
[Design Radiator_Towel Radiator] [tinyint] NOT NULL,
[Luxurious Heating Plate] [tinyint] NOT NULL,
[Built-in Oven with Heat Plate] [tinyint] NOT NULL,
[Built-in Microwave] [tinyint] NOT NULL,
[Luxurious Suction Hood] [tinyint] NOT NULL,
[No_ of extra Double Cupboards] [int] NOT NULL,
[Energy Perf_ Compensation] [tinyint] NOT NULL,
[No_ of built-in Heating Plates] [int] NOT NULL,
[No_ of lux_ Heating Plates] [int] NOT NULL,
[No_ of ceramic Heating Plates] [int] NOT NULL,
[No_ of built-in Furnaces] [int] NOT NULL,
[No_ of Combi-Ovens_Microwaves] [int] NOT NULL,
[No_ of Ovens with Heat Plate] [int] NOT NULL,
[No_ of built-in Microwaves] [int] NOT NULL,
[No_ of built-in Hoods] [int] NOT NULL,
[No_ of luxurious Suction Hoods] [int] NOT NULL,
[No_ of built-in Refrigerators] [int] NOT NULL,
[No_ of built-in Freezers] [int] NOT NULL,
[No_ of comb_ Freezers_Refrig_] [int] NOT NULL,
[No_ of built-in Dishwashers] [int] NOT NULL,
[No_ of luxury Taps Kitchen] [int] NOT NULL,
[No_ of thermost_ Taps Kitchen] [int] NOT NULL,
[No_ of double Sinks] [int] NOT NULL,
[No_ of built-in Sink Cabinets] [int] NOT NULL,
[No_ of Cabinets with Lighting] [int] NOT NULL,
[No_ of Whirlpools] [int] NOT NULL,
[No_ of luxury Taps Bath] [int] NOT NULL,
[No_ of thermost_ Taps Bath] [int] NOT NULL,
[No_ of Baths built-in Heating] [int] NOT NULL,
[No_ of aluminium Sliding Doors] [int] NOT NULL,
[No_ of Wall-_Floating Toilets] [int] NOT NULL,
[No_ of Design-_Towel Radiators] [int] NOT NULL,
[WOZ Value from WOZ Info] [numeric] (38, 20) NOT NULL,
[WOZ Deviation Reason] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Points Sink Kitchen Block] [numeric] (38, 20) NOT NULL,
[Maximum Rent Price] [numeric] (38, 20) NOT NULL,
[Protected City or Village View] [tinyint] NOT NULL,
[Maximum Rent Price Raise Perc_] [numeric] (38, 20) NOT NULL,
[Maximum Rent Price excl_ Raise] [numeric] (38, 20) NOT NULL,
[NoOfInductionCookers] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [i1_Staedion$Property_Valuation] ON [Huuraanpassing].[Staedion$Property Valuation] ([Eenheidnr_], [Ingangsdatum], [Einddatum]) INCLUDE ([Volgnummer]) ON [PRIMARY]
GO
