CREATE TABLE [Huuraanpassing].[staedion$element]
(
[timestamp] [timestamp] NOT NULL,
[Tabel] [int] NOT NULL,
[Clusternr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Eenheidnr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Volgnummer] [int] NOT NULL,
[Nr_] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[BTW-productboekingsgroep] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Omschrijving] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Soort] [int] NOT NULL,
[Samentelling] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Bedrag (LV)] [numeric] (38, 20) NOT NULL,
[Productboekingsgroep] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Elementsoort] [int] NOT NULL,
[Eenmalig] [tinyint] NOT NULL,
[Eenheid] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Afrekenen op basis van] [int] NOT NULL,
[Afrekenen met] [int] NOT NULL,
[Provisie over] [int] NOT NULL,
[Aantal] [numeric] (38, 20) NOT NULL,
[Inspringen] [int] NOT NULL,
[Eenheidprijs (LV)] [numeric] (38, 20) NOT NULL,
[Afdrukken] [tinyint] NOT NULL,
[Prioriteit] [int] NOT NULL,
[Verhogingsoort] [int] NOT NULL,
[Verhoging] [numeric] (38, 20) NOT NULL,
[Indexteller] [numeric] (38, 20) NOT NULL,
[Indexnoemer] [numeric] (38, 20) NOT NULL,
[Indexcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Indexeringsmethode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Subsidiabel] [tinyint] NOT NULL,
[Op huurverhoging afdrukken] [tinyint] NOT NULL,
[Afronding] [int] NOT NULL,
[Nauwkeurigheid] [numeric] (38, 20) NOT NULL,
[Belast (leeg)] [numeric] (38, 20) NOT NULL,
[Aantal belast (leeg)] [numeric] (38, 20) NOT NULL,
[Belast] [numeric] (38, 20) NOT NULL,
[Aantal belast] [numeric] (38, 20) NOT NULL,
[BTW] [numeric] (38, 20) NOT NULL,
[BTW (leeg)] [numeric] (38, 20) NOT NULL,
[Teller] [numeric] (38, 20) NOT NULL,
[Noemer] [numeric] (38, 20) NOT NULL,
[Bedrag] [numeric] (38, 20) NOT NULL,
[Eenheidprijs] [numeric] (38, 20) NOT NULL,
[Teller bepalen] [int] NOT NULL,
[Component] [int] NOT NULL,
[Schoorsteen] [tinyint] NOT NULL,
[Vast] [tinyint] NOT NULL,
[Verrekenbaar] [tinyint] NOT NULL,
[Verkorte omschrijving] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Administratie] [tinyint] NOT NULL,
[Leges] [tinyint] NOT NULL,
[Diversen] [tinyint] NOT NULL,
[Niet bij leegstandscontracten] [tinyint] NOT NULL,
[_ Administration Fee S&U] [numeric] (38, 20) NOT NULL,
[Rent Increase Amount] [numeric] (38, 20) NOT NULL,
[Global Dimension 1 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Global Dimension 2 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[From OnDelete Contract] [tinyint] NOT NULL,
[Cost Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Price Component Type Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Price Comp_ Det_Type Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [i1_Staedion$$element] ON [Huuraanpassing].[staedion$element] ([Tabel], [Eenheidnr_], [Eenmalig]) INCLUDE ([Volgnummer], [BTW-productboekingsgroep], [Soort], [Bedrag (LV)], [Elementsoort], [Administratie], [Leges], [Diversen]) ON [PRIMARY]
GO
