CREATE TABLE [Huuraanpassing].[staedion$Oge]
(
[timestamp] [timestamp] NOT NULL,
[Nr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Huisnr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Toevoegsel] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Straatnaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Postcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Plaats] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Type] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Status] [int] NOT NULL,
[Betreft] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Gewijzigd op] [datetime] NOT NULL,
[Zoeknaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[CheckRename] [tinyint] NOT NULL,
[Global Dimension 1 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Global Dimension 2 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Provisieperc_ verhuur] [numeric] (38, 20) NOT NULL,
[Provisieperc_ leegstand] [numeric] (38, 20) NOT NULL,
[Min_ bedrag provisie] [numeric] (38, 20) NOT NULL,
[Max_ bedrag provisie] [numeric] (38, 20) NOT NULL,
[Date Out of Management] [datetime] NOT NULL,
[Provisiebedrag] [numeric] (38, 20) NOT NULL,
[Technical Type] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Floor Applicable] [tinyint] NOT NULL,
[Floor] [int] NOT NULL,
[Decision Tree Type Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Responsibility Center] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Oud nummer] [nvarchar] (83) COLLATE Latin1_General_CI_AS NOT NULL,
[Rijksnummer] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[MIVA eenmalig] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[Streefhuurperc_ max_ huurprijs] [numeric] (38, 20) NOT NULL,
[VHE-algemeen] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Grondeigenaar] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Kadastrale gemeente] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Kadastrale Sectie] [nvarchar] (2) COLLATE Latin1_General_CI_AS NOT NULL,
[Kadastraal Nummer] [nvarchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[Kadastrale App_ index] [nvarchar] (5) COLLATE Latin1_General_CI_AS NOT NULL,
[CBS buurt] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Gebouwd] [datetime] NOT NULL,
[Gerenoveerd] [datetime] NOT NULL,
[Huidige labelconditie] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Nr_reeks] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Stemdeel] [numeric] (38, 20) NOT NULL,
[Breukdeel] [numeric] (38, 20) NOT NULL,
[Bijzondere doelgroepen] [tinyint] NOT NULL,
[Seniorenlabel] [tinyint] NOT NULL,
[Woning t_b_v_ asielzoekers] [tinyint] NOT NULL,
[Recht op subsidie] [tinyint] NOT NULL,
[Bedrijfswaarde SG] [numeric] (38, 20) NOT NULL,
[Bedrijfswaarde Wals] [numeric] (38, 20) NOT NULL,
[Deelgemeente] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Wijk] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Code huur _ max_ huurprijs] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Aanslagnummer OZB] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[OZB-grondslag] [numeric] (38, 20) NOT NULL,
[OZB-tarief Eigenaar] [numeric] (38, 20) NOT NULL,
[OZB-tarief Bewoner] [numeric] (38, 20) NOT NULL,
[OZB Eigenaar] [numeric] (38, 20) NOT NULL,
[OZB Bewoner] [numeric] (38, 20) NOT NULL,
[Waterschap] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Watersch_ Tarief Eigenaar] [numeric] (38, 20) NOT NULL,
[Watersch_ Tarief Bewoner] [numeric] (38, 20) NOT NULL,
[Waterschapslasten Eigenaar] [numeric] (38, 20) NOT NULL,
[Waterschapslasten Bewoner] [numeric] (38, 20) NOT NULL,
[Grondslag Waterschap] [numeric] (38, 20) NOT NULL,
[Belastingjaar] [int] NOT NULL,
[Rioolrecht] [numeric] (38, 20) NOT NULL,
[WOZ-Objectnummer] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Aanslagnummer waterschap] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Peildatum bedr_waarde SG] [datetime] NOT NULL,
[Peildatum bedr_waarde Wals] [datetime] NOT NULL,
[MIVA Jaarlijks] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[MIVA Bedrag] [numeric] (38, 20) NOT NULL,
[Date Sold] [datetime] NOT NULL,
[Aanbiedingsvorm verkoop] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[PMC Nr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Bouwnr_] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Juridische status] [int] NOT NULL,
[Jaar afloop erfpacht] [nvarchar] (4) COLLATE Latin1_General_CI_AS NOT NULL,
[Bedrijfsobject] [int] NOT NULL,
[Categorie] [int] NOT NULL,
[Reden inactief] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Begin exploitatie] [datetime] NOT NULL,
[Inactief] [tinyint] NOT NULL,
[Reden in exploitatie] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Einde exploitatie] [datetime] NOT NULL,
[Reden uit exploitatie] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Advertentienummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Advertentie-exportdatum] [datetime] NOT NULL,
[WoningNet Nr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[E-archief Nr_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Woonruimte] [int] NOT NULL,
[Voor-opname verplicht] [tinyint] NOT NULL,
[Streefhuurberekening] [int] NOT NULL,
[Streefhuur] [numeric] (38, 20) NOT NULL,
[Nto_huur tov_ max_huurprs_ (_)] [numeric] (38, 20) NOT NULL,
[Berekeningsjaar] [int] NOT NULL,
[Lager dan laagste normhuur] [tinyint] NOT NULL,
[OLA Straatnaam] [nvarchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Advertentienr_ Woonnet] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Distributiemethode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Verdelingsmethode] [int] NOT NULL,
[Huurbeleid] [int] NOT NULL,
[Beheerder] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Status VvE] [int] NOT NULL,
[Clusterstreefhuurbepaling] [tinyint] NOT NULL,
[Target Group Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Target Rent Method] [int] NOT NULL,
[Cadastral Area Hectare] [numeric] (38, 20) NOT NULL,
[Cadastral Area Are] [numeric] (38, 20) NOT NULL,
[Cadastral Area Centiare] [numeric] (38, 20) NOT NULL,
[Report To Energy Supplier] [tinyint] NOT NULL,
[EAN Code Gas] [nvarchar] (18) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Gas Registered] [datetime] NOT NULL,
[Date Gas Deregistered] [datetime] NOT NULL,
[EAN Code Electricity] [nvarchar] (18) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Electricity Registered] [datetime] NOT NULL,
[Date Electricity Deregistered] [datetime] NOT NULL,
[Country_Region Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[DAEB Indicator] [int] NOT NULL,
[Municipality Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Construction Year] [int] NOT NULL,
[Renovation Year] [int] NOT NULL,
[Common Area] [tinyint] NOT NULL,
[Type Description] [nvarchar] (70) COLLATE Latin1_General_CI_AS NOT NULL,
[No_ of Pre Inspections] [int] NOT NULL,
[Duration of Pre Inspections] [bigint] NOT NULL,
[Term First Inspection] [varchar] (32) COLLATE Latin1_General_CI_AS NOT NULL,
[No_ of Final Inspections] [int] NOT NULL,
[Duration of Final Inspections] [bigint] NOT NULL,
[Mutation Type] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[External Realty Object No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[External Customer No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Filter Building Block] [tinyint] NOT NULL,
[Selection Description] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Destination Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Living Form Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Quality Level Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Unit Detail Type Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Energy Label] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Target Group Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[MJO Id] [int] NOT NULL,
[Rent Increase Policy Type Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Net Rent Capping Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Target Rent Capping Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[In Care Home] [tinyint] NOT NULL,
[VERA Publication Module Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Publication Model Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Publ_ Detail Model Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Publ_ Intake Form Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[VERA Publ_ Contract Form Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[No_ of Other Non-Indep_ Units] [int] NOT NULL,
[Justify as House] [int] NOT NULL,
[CBS District Code] [nvarchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[CBS Neighborhood Code] [nvarchar] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[ExemptionTemporaryHouse] [tinyint] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [i1_staedion$oge] ON [Huuraanpassing].[staedion$Oge] ([Nr_], [Woonruimte]) ON [PRIMARY]
GO
