CREATE TABLE [Huuraanpassing].[staedion$OGE Rent Increase]
(
[timestamp] [timestamp] NOT NULL,
[Realty Object No_] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Period Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Contract Type] [int] NOT NULL,
[Contract Entry No_] [int] NOT NULL,
[Period Description] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Period Starting Date] [datetime] NOT NULL,
[Rent Incr_ Policy Type Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Rent Incr_ Policy Type Descr_] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Basic Increase Percentage] [numeric] (38, 20) NOT NULL,
[Increase Percentage Precision] [int] NOT NULL,
[Income Class Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Income Dep_ Incr_ Percentage] [numeric] (38, 20) NOT NULL,
[Total Increase Percentage] [numeric] (38, 20) NOT NULL,
[Batch Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Batch Description] [nvarchar] (85) COLLATE Latin1_General_CI_AS NOT NULL,
[DAEB Indicator] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Liberalisation Limit] [numeric] (38, 20) NOT NULL,
[Liberalized Contract] [tinyint] NOT NULL,
[Target Rent Percentage] [numeric] (38, 20) NOT NULL,
[Target Rent] [numeric] (38, 20) NOT NULL,
[Maximum Rent Price] [numeric] (38, 20) NOT NULL,
[Valuation Points] [numeric] (38, 20) NOT NULL,
[Current Net Rent] [numeric] (38, 20) NOT NULL,
[Net Rent Capping Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Net Rent Capping Type] [int] NOT NULL,
[Net Rent Capping Description] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Net Rent Capping Amount] [numeric] (38, 20) NOT NULL,
[Market Rent] [numeric] (38, 20) NOT NULL,
[Subsidy Service Amt_ Included] [tinyint] NOT NULL,
[Subsidy Service Amount] [numeric] (38, 20) NOT NULL,
[Net Rent Capping Line Perc_] [numeric] (38, 20) NOT NULL,
[Net Rent Capping Line Type] [int] NOT NULL,
[Capping Correction Amount] [numeric] (38, 20) NOT NULL,
[Before Capping Net Rent] [numeric] (38, 20) NOT NULL,
[After Capping Net Rent] [numeric] (38, 20) NOT NULL,
[Effective Increase Percentage] [numeric] (38, 20) NOT NULL,
[Effective Capping Amount] [numeric] (38, 20) NOT NULL,
[New Net Rent] [numeric] (38, 20) NOT NULL,
[Calculated Increase Perc_] [numeric] (38, 20) NOT NULL,
[Increase Perc_ Correction] [numeric] (38, 20) NOT NULL,
[Curr_ Net Rent Max_ Rent Ratio] [numeric] (38, 20) NOT NULL,
[Curr_ Net Rent Lib_Limit Ratio] [numeric] (38, 20) NOT NULL,
[New Net Rent Max_ Rent Ratio] [numeric] (38, 20) NOT NULL,
[New Net Rent Lib_ Limit Ratio] [numeric] (38, 20) NOT NULL,
[Curr_ Net Rent Mrkt Rent Ratio] [numeric] (38, 20) NOT NULL,
[New Net Rent Market Rent Ratio] [numeric] (38, 20) NOT NULL,
[Curr_ Net Rent Trg Rent Ratio] [numeric] (38, 20) NOT NULL,
[New Net Rent Target Rent Ratio] [numeric] (38, 20) NOT NULL,
[Calculation Remarks] [image] NULL,
[Exception Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Exception Text] [image] NULL,
[Batch Choice] [int] NOT NULL,
[Capping Choice] [int] NOT NULL,
[Capping Amount Type] [int] NOT NULL,
[Eff_ Capping Amt_ Type] [int] NOT NULL,
[Preparation Date-Time] [datetime] NOT NULL,
[Calculation Date-Time] [datetime] NOT NULL,
[Capping at Maximum Rent Price] [int] NOT NULL,
[Decr_ due to Capping Allowed] [tinyint] NOT NULL,
[Rent Price Reference Date] [datetime] NOT NULL,
[Contract Rent Increase Date] [datetime] NOT NULL,
[Realty Object Status] [int] NOT NULL,
[Realty Object Type Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Realty Object Type Descr_] [nvarchar] (70) COLLATE Latin1_General_CI_AS NOT NULL,
[Realty Object Technical Type] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Realty Object Type CorpoData] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Start Date Rental Contract] [datetime] NOT NULL,
[Processing Status] [int] NOT NULL,
[Calculation Code] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Finalization Date-Time] [datetime] NOT NULL,
[New Contract Entry No_] [int] NOT NULL,
[Capping Applied] [tinyint] NOT NULL,
[Rent Incr_ Narration Codes1] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Rent Incr_ Narration Codes2] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Rent Incr_ Narration Codes3] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Municipality Code] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Municipality Name] [nvarchar] (250) COLLATE Latin1_General_CI_AS NOT NULL,
[Global Dimension 1 Code] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Incr_ Net Rent when Rent Disc_] [tinyint] NOT NULL,
[Configured Incr_ Perc_ is Max_] [tinyint] NOT NULL,
[Income Dependent Increase Amt_] [numeric] (38, 20) NOT NULL,
[RentIncreaseDate] [datetime] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [id_staedion$OGE Rent Increase] ON [Huuraanpassing].[staedion$OGE Rent Increase] ([Period Code]) INCLUDE ([Realty Object No_], [Rent Incr_ Policy Type Code], [Batch Code], [Current Net Rent], [Net Rent Capping Code], [New Net Rent], [New Contract Entry No_]) ON [PRIMARY]
GO
