CREATE TABLE [Onderhoud].[VerzoekenOrdersTaken TEST]
(
[Verzoek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Order] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Verzoek - status] [varchar] (39) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - onderhoudstype] [nvarchar] (19) COLLATE Latin1_General_CI_AS NULL,
[Verzoek - huurdernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - clusternummer] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - omschrijving] [nvarchar] (150) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - datum invoer] [datetime] NOT NULL,
[Verzoek - ingevoerd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - oorzaakcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Verzoek - uiterst gereed datum] [datetime] NOT NULL,
[Verzoek - Meldingsdatum] [datetime] NOT NULL,
[Verzoek - Meldingstijd] [datetime] NOT NULL,
[Verzoek - Ingevoerd vanuit] [nvarchar] (13) COLLATE Latin1_General_CI_AS NULL,
[TAAK - aanmaakdatum] [datetime] NULL,
[TAAK - aanmaaktijd] [datetime] NULL,
[TAAK - uiterste datum] [datetime] NULL,
[Order - werkelijke startdatum] [datetime] NULL,
[Order - datum technisch gereed] [datetime] NULL,
[Order - leverancier] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Order - eigen dienst] [tinyint] NULL,
[Order - bekwaamheidscode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Order - afspraakdatum] [datetime] NULL,
[Order - aanmaakdatum] [datetime] NULL,
[Order - status] [nvarchar] (39) COLLATE Latin1_General_CI_AS NULL,
[Order - kostencode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Order - acceptatiedatum] [datetime] NULL,
[Order - gunningsdatum] [datetime] NULL,
[Order - starttijd van] [datetime] NULL,
[Order - starttijd tot] [datetime] NULL,
[Order - reden na uiterste datum] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Order - weigeringsreden] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Order - weigeringsdatum] [datetime] NULL,
[Order - uiterst gereed datum] [datetime] NULL,
[Order - afrondcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Order - urgent] [int] NULL,
[Order - urgentiecode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - afrondcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - afrondcode oms] [nvarchar] (85) COLLATE Latin1_General_CI_AS NULL,
[Taak - geplande resource] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Taak - voornaam geplande resource] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Taak - afgehandeld per] [datetime] NULL,
[Taak - bekwaamheid] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Taak - bekwaamheidscode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - standaard taakcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - sjablooncode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - gebrek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - garantie] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Taak - status] [nvarchar] (16) COLLATE Latin1_General_CI_AS NULL,
[Taak - kostencode] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Taak - oorzaakcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - ruimtesoortcode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak - bedrag incl btw] [numeric] (38, 20) NULL,
[Taak - inkoopwijze] [varchar] (15) COLLATE Latin1_General_CI_AS NULL,
[Komt voor in uitvallijst] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Niet versturen - sjabloon uitzonderingslijst wordt aangelopen] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Verzoek - Hyperlink] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Laaddatum] [date] NULL
) ON [PRIMARY]
GO
