CREATE TABLE [Onderhoud].[Projectposten]
(
[Projectpost_id] [int] NOT NULL IDENTITY(1, 1),
[Bedrijf_id] [int] NULL,
[Timestamp] [varbinary] (8) NULL,
[Volgnummer] [int] NULL,
[Onderhoudsorder/Projectnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Boekdatum] [date] NULL,
[Boekstuknr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Regelsoort] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Resource_id] [int] NULL,
[Artikel_id] [int] NULL,
[Rekening_id] [int] NULL,
[Projectsoort] [varchar] (19) COLLATE Latin1_General_CI_AS NULL,
[Omschrijving] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Omschrijving 2] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Aantal] [decimal] (12, 2) NULL,
[Directe kosten per eenheid] [decimal] (12, 2) NULL,
[Eenheidskosten] [decimal] (12, 2) NULL,
[Totale kostprijs] [decimal] (12, 2) NULL,
[Eenheidsprijs] [decimal] (12, 2) NULL,
[Totale prijs] [decimal] (12, 2) NULL,
[Resource groep_id] [int] NULL,
[Meeteenheid_id] [int] NULL,
[Vestiging_id] [int] NULL,
[Voorraadboekingsgroep_id] [int] NULL,
[Dimensiewaarde 1_id] [int] NULL,
[Dimensieset_id] [int] NULL,
[Gebruiker] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Bron_id] [int] NULL,
[Gebruiksoort] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[Productboekingsgroep_id] [int] NULL,
[Document datum] [date] NULL,
[Extern documentnummer] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Regelbedrag] [decimal] (12, 2) NULL,
[Kostprijs] [decimal] (12, 2) NULL,
[Totale kosten] [decimal] (12, 2) NULL,
[Totaalprijs] [decimal] (12, 2) NULL,
[Regel kortingsbedrag] [decimal] (12, 2) NULL,
[Boekingssoort] [varchar] (17) COLLATE Latin1_General_CI_AS NULL,
[Resource boekingspost] [int] NULL,
[Artikel boekingspost] [int] NULL,
[Grootboek boekingspost] [int] NULL,
[Regelkortingspercentage] [decimal] (12, 2) NULL,
[Regeltype] [varchar] (23) COLLATE Latin1_General_CI_AS NULL,
[Oorspronkelijke kostprijs] [decimal] (12, 2) NULL,
[Oorspronkelijke totale kostprijs] [decimal] (12, 2) NULL,
[Aantal per meeteenheid] [decimal] (12, 2) NULL,
[Aantal (basis)] [decimal] (12, 2) NULL,
[Clusternr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Collectiefnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Kostencode gecorrigeerd] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Kostprijs exclusief toeslag] [decimal] (12, 2) NULL,
[Leefbaarheidsdossiernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Leefbaarheid] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Fiatteur] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Btwproductboekingsgroep_id] [int] NULL,
[Externe kosten excl. btw] [decimal] (12, 2) NULL,
[Taakspecificatiesoort] [varchar] (14) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsverzoek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsverzoek_id] [int] NULL
) ON [PRIMARY]
GO
