CREATE TABLE [Onderhoud].[Onderhoudsorder]
(
[Onderhoudsorder_id] [int] NOT NULL IDENTITY(1, 1),
[Geldig van] [date] NULL,
[Geldig tot] [date] NULL,
[Verwijderd] [bit] NULL,
[Huidig record] [bit] NULL,
[Bedrijf_id] [int] NULL,
[Timestamp] [binary] (8) NULL,
[Onderhoudsorder] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Leveranciernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsverzoek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Omschrijving] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[Aanmaakdatum] [date] NULL,
[Aangemaakt door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Laatste wijziging] [date] NULL,
[Gewijzigd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Orderstatus_id] [int] NULL,
[Kostencode_id] [int] NULL,
[Oude kostencode_id] [int] NULL,
[Duur] [decimal] (12, 2) NULL,
[Vroegste startdatum] [date] NULL,
[Uiterste gereeddatum] [date] NULL,
[Datum technisch gereed] [date] NULL,
[Afspraakdatum] [date] NULL,
[Tijd van] [time] (0) NULL,
[Tijd tot] [time] (0) NULL,
[Overschrijdingsreden_id] [int] NULL,
[Aantal resources] [int] NULL,
[Bekwaamheid_id] [int] NULL,
[Urgentie_id] [int] NULL,
[Extern referentienummer] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Datum gegund] [date] NULL,
[Acceptatiedatum] [date] NULL,
[Weigeringsdatum] [date] NULL,
[Weigeringsreden_id] [int] NULL,
[Werkelijke startdatum] [date] NULL,
[Inkoopwijze] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Verplichting] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Verplichting bij gunning] [decimal] (12, 2) NULL,
[Verkoopwijze] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Verkoopprijs] [decimal] (12, 2) NULL,
[Bijlagenset_id] [int] NULL,
[Aantal bijlagen] [int] NULL,
[Omschrijvingen set] [int] NULL,
[Inkoopordernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Percentage naar G rekening] [decimal] (6, 2) NULL,
[Bedrag naar G rekening] [decimal] (12, 2) NULL,
[Btw verlegd] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Afrondcode_id] [int] NULL,
[Offertenummer leverancier] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Ordernummer leverancier] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Bedrag arbeid btw hoog] [decimal] (12, 2) NULL,
[Bedrag arbeid btw laag] [decimal] (12, 2) NULL,
[Bedrag arbeid btw vrijgesteld] [decimal] (12, 2) NULL,
[Bedrag materiaal btw hoog] [decimal] (12, 2) NULL,
[Bedrag materiaal btw laag] [decimal] (12, 2) NULL,
[Bedrag materiaal btw vrijgesteld] [decimal] (12, 2) NULL,
[Bedrag reiskosten btw hoog] [decimal] (12, 2) NULL,
[Bedrag reiskosten btw laag] [decimal] (12, 2) NULL,
[Bedrag reiskosten btw vrijgesteld] [decimal] (12, 2) NULL,
[Bedrag diverse kosten btw hoog] [decimal] (12, 2) NULL,
[Bedrag diverse kosten btw laag] [decimal] (12, 2) NULL,
[Bedrag diverse kosten btw vrijgesteld] [decimal] (12, 2) NULL,
[Bedrag totaal btw hoog] [decimal] (12, 2) NULL,
[Bedrag totaal btw laag] [decimal] (12, 2) NULL,
[Bedrag totaal btw vrijgesteld] [decimal] (12, 2) NULL,
[Kostenspecificatie definitief] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[In planner] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Planner afgerond] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudssoort] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Aangemaakt zonder kostenspecificatie] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [cidx_Onderhoudsorder_Onderhoudsorder_id_bedrijf_id] ON [Onderhoud].[Onderhoudsorder] ([Bedrijf_id], [Onderhoudsorder_id]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_Onderhoudsorder_Onderhoudsorder_id_huidig_record] ON [Onderhoud].[Onderhoudsorder] ([Onderhoudsorder_id]) INCLUDE ([Huidig record]) ON [PRIMARY]
GO
