CREATE TABLE [Onderhoud].[Onderhoudstaak]
(
[Onderhoudstaak_id] [int] NOT NULL IDENTITY(1, 1),
[Geldig van] [date] NULL,
[Geldig tot] [date] NULL,
[Verwijderd] [bit] NULL,
[Huidig record] [bit] NULL,
[Bedrijf_id] [int] NULL,
[Timestamp] [binary] (8) NULL,
[Onderhoudsverzoek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsverzoek_id] [int] NULL,
[Onderhoudstaak] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Taak nr] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Omschrijving] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[Aanmaakdatum] [date] NULL,
[Aanmaaktijd] [time] (0) NULL,
[Handmatig] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Reparatiesjabloon_id] [int] NULL,
[Oorzaak_id] [int] NULL,
[Onderhoudstaakstatus_id] [int] NULL,
[Kostencode_id] [int] NULL,
[Bouwelement_id] [int] NULL,
[Onderdeel_id] [int] NULL,
[Gebrek_id] [int] NULL,
[Ruimtesoort_id] [int] NULL,
[Aantal] [decimal] (12, 2) NULL,
[Meeteenheid_id] [int] NULL,
[Eenheidskosten] [decimal] (12, 2) NULL,
[Bedrag] [decimal] (12, 2) NULL,
[Bedrag incl. btw] [decimal] (12, 2) NULL,
[Uitgevoerd door] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Bekwaamheid_id] [int] NULL,
[Aantal bekwaamheden] [int] NULL,
[Leveranciernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Standaard aantal uren] [decimal] (12, 2) NULL,
[Totaal aantal uren] [decimal] (12, 2) NULL,
[Onderhoudsorder] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsorder_id] [int] NULL,
[Afrondcode_id] [int] NULL,
[Doorbelasten aan] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Door te belasten] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Doorbelasting geboekt] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Doorbelasting gecorrigeerd] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Doorbelasten aan klantnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Verkoopwijze] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Huurder akkoord met kosten] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Percentage doorbelasting] [decimal] (12, 2) NULL,
[Eenheidsprijs] [decimal] (12, 2) NULL,
[Eenheidsprijs incl. btw] [decimal] (12, 2) NULL,
[Bedrag doorbelasting excl. btw] [decimal] (12, 2) NULL,
[Bedrag doorbelasting incl. btw] [decimal] (12, 2) NULL,
[Afgesloten door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Afgesloten op] [date] NULL,
[Ingevoerd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Leefbaarheidsdossiernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Bijlagenset_id] [int] NULL,
[Aantal bijlagen] [int] NULL,
[Omschrijvingenset_id] [int] NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Collectiefnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Clusternr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Urgentie_id] [int] NULL,
[Uiterste datum] [date] NULL,
[Meldernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[huurdernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Inspectieverzoek] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Inkoopwijze] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Garantie] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Taak planbaar] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Melddatum] [date] NULL,
[Aantal uren] [decimal] (12, 2) NULL,
[Resources] [decimal] (12, 2) NULL,
[Materiaalkosten] [decimal] (12, 2) NULL,
[Grootboek] [decimal] (12, 2) NULL,
[Totale kosten] [decimal] (12, 2) NULL,
[Geboekte opbrengsten taak] [decimal] (12, 2) NULL,
[Resourceverbruik aantal (basis)] [decimal] (12, 2) NULL,
[Resourceverbruik kostprijs] [decimal] (12, 2) NULL,
[Materiaalverbruik kostprijs] [decimal] (12, 2) NULL,
[Verbruik kostprijs] [decimal] (12, 2) NULL,
[Aantal projectposten] [int] NULL
) ON [PRIMARY]
GO
