CREATE TABLE [Onderhoud].[Onderhoudsverzoek]
(
[Onderhoudsverzoek_id] [int] NOT NULL IDENTITY(1, 1),
[Geldig van] [date] NULL,
[Geldig tot] [date] NULL,
[Verwijderd] [bit] NULL,
[Huidig record] [bit] NULL,
[Bedrijf_id] [int] NULL,
[Timestamp] [binary] (8) NULL,
[Onderhoudsverzoek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Omschrijving] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[Eenheidnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Meetwaarde_id] [int] NULL,
[Collectiefnr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Collectief object_id] [int] NULL,
[Clusternr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsverzoekstatus_id] [int] NULL,
[Afwijsreden_id] [int] NULL,
[Melddatum] [date] NULL,
[Meldtijd] [time] (0) NULL,
[Urgentie_id] [int] NULL,
[Uiterste uitvoerdatum] [date] NULL,
[Preventief] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudssoort_id] [int] NULL,
[Meldernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Huurdernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Opzegreden_id] [int] NULL,
[Klachtsoort_id] [int] NULL,
[Leefbaarheidsdossiernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Beheerdernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Bijlagenset_id] [int] NULL,
[Aantal bijlagen] [int] NULL,
[Omschrijvingenset_id] [int] NULL,
[Ingevoerd door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Aangemaakt vanuit] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Afgesloten op] [date] NULL,
[Afgesloten door] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Inspectie] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Clusterinspecteur] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Inspecteur] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Contract volgnr] [int] NULL,
[Cluster budgethouder] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DO budgethouder] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Behandelend medewerker] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[In VvE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Doorgezet naar VvE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[VvE] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Communicatiewijze_id] [int] NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [cidx_onderhoudsverzoek_Onderhoudsverzoek_id_bedrijf_id] ON [Onderhoud].[Onderhoudsverzoek] ([Bedrijf_id], [Onderhoudsverzoek_id]) ON [PRIMARY]
GO
