CREATE TABLE [Onderhoud].[Offerte TEST]
(
[Offerte_id] [int] NOT NULL IDENTITY(1, 1),
[Geldig van] [datetime] NULL,
[Geldig tot] [datetime] NULL,
[Gegenereerd op] [datetime] NULL,
[Gewijzigd op] [datetime] NULL,
[Verwijderd op] [datetime] NULL,
[Huidig record] [bit] NULL,
[Bedrijf_id] [int] NULL,
[Timestamp] [binary] (8) NULL,
[Offertenr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Offerte document datum] [date] NULL,
[Offerte orderdatum] [date] NULL,
[Offertebedrag incl btw] [decimal] (12, 2) NULL,
[Offerte verplichting] [decimal] (12, 2) NULL,
[Omschrijving] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[Orderstatus_id] [int] NULL,
[Offertenummer leverancier] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Ordernummer leverancier] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Inkoper indiening offerte] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Werkwijze] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Leveranciers status] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Leveranciernr] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Gebruiker indiening offerte] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Tijdstip bijlage toegevoegd] [datetime] NULL,
[Tijdstip indiening offerte door leverancier] [datetime] NULL,
[Gebruiker indiening offerte door leverancier] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Datum onderhoudsorder aangemaakt] [date] NULL,
[Onderhoudsorder aangemaakt] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsorder] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Onderhoudsverzoek] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Kostencode_id] [int] NULL,
[Verplichting bij gunning] [decimal] (8, 2) NULL,
[Attachment Set ID] [int] NULL
) ON [PRIMARY]
GO
