CREATE TABLE [Projecten].[InvulsheetOpleveringEnStart]
(
[Soort Project] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Project] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Jaarplan] [float] NULL,
[KPI] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[start 01] [float] NULL,
[start 02] [float] NULL,
[start 03] [float] NULL,
[start 04] [float] NULL,
[start 05] [float] NULL,
[start 06] [float] NULL,
[start 07] [float] NULL,
[start 08] [float] NULL,
[start 09] [float] NULL,
[start 10] [float] NULL,
[start 11] [float] NULL,
[start 12] [float] NULL,
[oplevering 01] [float] NULL,
[oplevering 02] [float] NULL,
[oplevering 03] [float] NULL,
[oplevering 04] [float] NULL,
[oplevering 05] [float] NULL,
[oplevering 06] [float] NULL,
[oplevering 07] [float] NULL,
[oplevering 08] [float] NULL,
[oplevering 09] [float] NULL,
[oplevering 10] [float] NULL,
[oplevering 11] [float] NULL,
[oplevering 12] [float] NULL,
[Opmerking] [varchar] (37) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
