CREATE TABLE [RekeningCourant].[HistorieDetailsVoorzieningTRASH]
(
[Maand] [float] NULL,
[Maand-jaar] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Jaar] [float] NULL,
[Datum] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Bedrijf] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Klantnr] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Klantboek#gr#] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Naam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[BOG] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Lopend contract] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[minnelijke schikking] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[WSNP] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[(WSNP oud)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Bet# reg] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Bij deurw#] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Prio#] [float] NULL,
[Regel] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Saldo] [float] NULL,
[Openst# saldo] [float] NULL,
[Vooruitbet#] [float] NULL,
[Rekensaldo] [float] NULL,
[%] [float] NULL,
[Voorziening] [float] NULL,
[OGEHnr] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Tech# type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[OGE adres] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Wijk] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Buurt] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Complex] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Complex naam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Verhuurteam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Thuisteam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
