CREATE TABLE [Staging].[kcm]
(
[id] [int] NOT NULL,
[ingevuldtimestamp] [datetime2] NULL,
[ingevulddate] [datetime2] NULL,
[ingevuld_date_sk] [float] NULL,
[huurdernr] [nvarchar] (12) COLLATE Latin1_General_CI_AS NULL,
[ext_id] [int] NULL,
[telefoonnr1] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[telefoonnr2] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[telefoonnr3] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[emailadres] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[postcode] [nvarchar] (8) COLLATE Latin1_General_CI_AS NULL,
[straatnaam] [nvarchar] (120) COLLATE Latin1_General_CI_AS NULL,
[huisnr] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[stad] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[eenheidnr] [nvarchar] (13) COLLATE Latin1_General_CI_AS NULL,
[clusternr] [nvarchar] (8) COLLATE Latin1_General_CI_AS NULL,
[divisie] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[klantbedrijf] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[huurdernaam] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[aanhef_huurdernaam] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[gegenereerd] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[eenheidadres] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[clusternaam] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[bouwblok] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[bouwbloknaam] [nvarchar] (68) COLLATE Latin1_General_CI_AS NULL,
[voelt_zich_thuis] [bit] NULL,
[thuisgevoel_score] [int] NULL,
[thuisgevoel_verklaring] [nvarchar] (4000) COLLATE Latin1_General_CI_AS NULL,
[woningkwaliteit_score] [int] NULL,
[staat_keukenbadkamertoilet_score] [int] NULL,
[energiezuinig_score] [int] NULL,
[gehorig_score] [int] NULL,
[gevoelstemperatuur_score] [int] NULL,
[prijskwaliteit_score] [int] NULL,
[inbraakveilig_score] [int] NULL,
[algemene_ruimten_aanwezig] [bit] NULL,
[algemene_ruimten_score] [int] NULL,
[algemene_ruimten_netheid_score] [int] NULL,
[algemene_ruimten_verlichting_score] [int] NULL,
[algemene_ruimten_veilig_score] [int] NULL,
[buurt_score] [int] NULL,
[buurt_overlast_score] [int] NULL,
[buurt_netheid_score] [int] NULL,
[buurt_veilig_score] [int] NULL,
[buurt_contact_score] [int] NULL,
[buurt_bereidtotinzet_choice] [nvarchar] (4000) COLLATE Latin1_General_CI_AS NULL,
[vragen_overgeslagen] [bit] NULL,
[verhuizen_binnen_jaar_choice] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[gezinsamenstelling_choice] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[aantal_personen_inwonend_choice] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[financieel_rondkomen_score] [nvarchar] (4000) COLLATE Latin1_General_CI_AS NULL,
[financiele_situatie_choice] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[gezondheid_omschrijving_choice] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[hulp_afhankelijk_choice] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[suggestie_gegeven] [bit] NULL,
[andere_suggestie_text] [nvarchar] (4000) COLLATE Latin1_General_CI_AS NULL,
[gegevenskoppeling_toestemming] [bit] NULL,
[contact_toestemming] [bit] NULL
) ON [PRIMARY]
GO
