IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'STAEDION\svcPowerBI')
CREATE LOGIN [STAEDION\svcPowerBI] FROM WINDOWS
GO
CREATE USER [STAEDION\svcPowerBI] FOR LOGIN [STAEDION\svcPowerBI]
GO
