IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'STAEDION\PowerBi')
CREATE LOGIN [STAEDION\PowerBi] FROM WINDOWS
GO
CREATE USER [STAEDION\PowerBi] FOR LOGIN [STAEDION\PowerBi]
GO
